exports.keywords = [
  'gloves',
  'torch',
  'safety boots',
  'nitrile gloves',
  'tape measure',
  'padlock',
  'wd40',
  'safety glasses',
  'coffee',
  'socket set',
  'hammer',
  'blue roll',
  'cable ties',
  'boots',
  'safety shoes',
  'stanley knife',
  'batteries',
  'wire brush',
  'heater',
  'masking tape',
  'first aid',
  'brush',
  'rags',
  'bin',
  'de icer',
  'pliers',
  'allen keys',
  'disposable gloves',
  'tape',
  'scraper',
  'sugar',
  'broom',
  'screen wash',
  'ear plugs',
  'toilet roll',
  'adjustable spanner',
  'tool box',
  'grease gun',
  'scissors',
  'ear defenders',
  'aa batteries',
  'paint brush',
  'kettle',
  'paint',
  'loctite',
  'torque wrench',
  'wipes',
  'chair',
  'trousers',
  'head torch',
  'knife',
  'screwdriver set',
  'drill bits',
  'screwdriver',
  'extension lead',
  'face mask',
  'dewalt',
  'shovel',
  'trolley',
  'bleach',
  'plasters',
  'vernier',
  'diary',
  'screenwash',
  'spill kit',
  'drill',
  'eye wash',
  'spanner',
  'swarfega',
  'allen key set',
  'allen key',
  'face masks',
  'stapler',
  'spanner set',
  'KEN6025500',
  'washing up liquid',
  'grease',
  'battery',
  'cutting disc',
  'ken6025500',
  'a4 paper',
  'hacksaw',
  'funnel',
  'mop',
  'first aid kit',
  'uvex',
  'vice',
  'rock salt',
  'bucket',
  'SEN5940580K',
  'ladder',
  'storage',
  'toolbox',
  'paint brushes',
  'double sided tape',
  'WD40',
  'spray bottle',
  'silver steel',
  'chain',
  'pens',
  'latex gloves',
  'magnet',
  'dremel',
  'salt',
  'wera',
  'cabinet',
  'cable tie',
  'tool bag',
  'grinder',
  'staples',
  'milwaukee',
  'makita',
  'drill bit',
  'duct tape',
  'de-icer',
  'hi vis',
  'microwave',
  'aaa batteries',
  'pry bar',
  'ratchet',
  'mask',
  'fleece',
  'socket',
  'spray paint',
  'padlocks',
  'tap wrench',
  'office chair',
  'fridge',
  'hand soap',
  'dymo',
  'super glue',
  'brake cleaner',
  'tool chest',
  'safety trainers',
  'bin bags',
  'hose',
  'stanley blades',
  'whiteboard',
  'snips',
  'mallet',
  'spill',
  'clock',
  'jacket',
  'steel rule',
  'welding',
  'spirit level',
  'bubble wrap',
  'racking',
  'sweeping brush',
  'waste bin',
  'water',
  'key safe',
  'shrink wrap',
  'led torch',
  'loctite 243',
  'pallet truck',
  'kennedy',
  'toilet rolls',
  'heat gun',
  'knee pads',
  'pipe wrench',
  'hacksaw blades',
  'tap',
  'vacuum',
  'scotch brite',
  'bump cap',
  'dustpan',
  'milk',
  'air gun',
  'deb',
  'floor paint',
  'hex key set',
  'paint roller',
  'soap',
  'impact socket',
  'bolle',
  'locker',
  'GLOVES',
  'cr2032',
  'calculator',
  'ambersil',
  'tape dispenser',
  'mirror',
  'scotchbrite',
  'die grinder',
  'masks',
  'files',
  'lockers',
  'rigger gloves',
  'chisel',
  'mop bucket',
  'clamp',
  'hi viz',
  'glove',
  'bins',
  'unilite',
  'flap disc',
  'steps',
  'tarpaulin',
  'KEN0751160',
  'ruler',
  'insoles',
  'aa battery',
  'hoover',
  'tap set',
  'hand sanitiser',
  'heaters',
  'sharpie',
  'circlip pliers',
  'silicone',
  'drill set',
  'bott',
  'storage box',
  'magnets',
  'air hose',
  'file',
  'hard hat',
  'paper',
  'tea',
  'key steel',
  'digital caliper',
  'aaa',
  'knipex',
  'clipboard',
  'bags',
  'dust pan',
  'stanley',
  'chairs',
  'copper hammer',
  'floor cleaner',
  'hex key',
  'ptfe tape',
  'coverall',
  'electrical tape',
  'ground flat stock',
  'drill bit set',
  'white board',
  'superglue',
  'adjustable wrench',
  'micrometer',
  'ratchet spanner',
  'air freshener',
  'angle grinder',
  'spanners',
  'glass cleaner',
  'ratchet strap',
  'tea bags',
  'mop head',
  'caliper',
  'facom',
  'reamer',
  'barrier',
  'strapping',
  'sellotape',
  'helicoil',
  'scales',
  'impact wrench',
  'hand brush',
  'feeler gauge',
  'square',
  'countersink',
  'brushes',
  'hole saw',
  'hand towels',
  'combination spanner',
  'lr44',
  'screwdrivers',
  'bahco',
  'welding gloves',
  'deicer',
  'ladders',
  'safety knife',
  'rivet',
  'shelving',
  'torque',
  'toilet brush',
  'mouse',
  'pipe cutter',
  'banding',
  'blow gun',
  'clamps',
  'overalls',
  'face shield',
  'rivet gun',
  'sling',
  'airline',
  'fan heater',
  'tin snips',
  'punch',
  'plier set',
  'coveralls',
  'barrier cream',
  'rule',
  'degreaser',
  'wheelie bin',
  'cupboard',
  'drills',
  'shoes',
  'jobber drill',
  'wd 40',
  'safety boot',
  'hand cleaner',
  'rope',
  'brown tape',
  'screws',
  'sponge',
  'breaker bar',
  'insulation tape',
  'labels',
  'NITRILE GLOVES',
  '3m',
  'saw',
  'impact driver',
  'thermometer',
  'file set',
  'centre punch',
  'glasses',
  'mole grips',
  'wall planner',
  'moldex',
  'solder',
  'wire cutters',
  'dust mask',
  'hex keys',
  'air freshner',
  'adblue',
  'long nose pliers',
  'dowel',
  'step ladder',
  'holesaw',
  'bottle jack',
  'keyboard',
  'glue',
  'pressure washer',
  'pen',
  'tuffsafe',
  'side cutters',
  'lock',
  'work trousers',
  'g clamp',
  'circlip',
  'flap wheel',
  'cutters',
  'kobe',
  'digital vernier',
  'paint pen',
  'spray bottles',
  'hand wash',
  'rubber mallet',
  'torches',
  'inspection lamp',
  '92-600',
  'cutting discs',
  'karcher',
  'pallet wrap',
  'waterproof trousers',
  'toaster',
  'dust sheet',
  'AA batteries',
  'SAFETY GLASSES',
  'taps',
  'parcel tape',
  'toilet cleaner',
  'ffp3',
  'cordless drill',
  'bin liners',
  'litter picker',
  'light',
  'eyewash',
  'goggles',
  'mouse mat',
  'wd-40',
  'rigger boots',
  'bag',
  '9v battery',
  'toilet',
  'packing tape',
  'snow shovel',
  'salt spreader',
  'COFFEE',
  'ice scraper',
  'bench grinder',
  'visor',
  'ptfe',
  'table',
  'ratchet straps',
  'vernier caliper',
  'dewalt drill',
  'air line',
  'coat',
  'scrapers',
  'stool',
  'rocol',
  'hacksaw blade',
  'safety shoe',
  'jerry can',
  'floor tape',
  'laminator',
  'thermal gloves',
  'vacuum cleaner',
  'hose pipe',
  'hi vis vest',
  'wire wheel',
  'aa',
  'insole',
  'welding mask',
  'signs',
  'ken5822610',
  'grit',
  'key cabinet',
  'sen0330600',
  'desk',
  'tork',
  'CABLE TIES',
  'overall',
  'screw extractor',
  'hand saw',
  'punch set',
  'lamp',
  'portwest',
  'led lenser',
  'hazard tape',
  'AAA',
  'allen',
  'extension cable',
  'wrench',
  'cable',
  'blow torch',
  'ken6025730',
  'tool kit',
  'planner',
  'jug',
  'fire extinguisher',
  'KEN5822610',
  'jack',
  'shim',
  'hand wipes',
  'grub screw',
  'henry',
  'sprayer',
  'hose reel',
  'sanitiser',
  'multimeter',
  'claw hammer',
  'barrier tape',
  'hole punch',
  'wet and dry',
  'mat',
  'ear',
  'ac90',
  'hasp',
  'paper towels',
  'paint marker',
  'AA BATTERIES',
  'washer',
  'soldering iron',
  'extension leads',
  'lump hammer',
  'transformer',
  'aaa battery',
  'screw driver set',
  'stretch wrap',
  'black bags',
  'set square',
  'paint rollers',
  'chuck',
  'KEN5185420',
  'ppe',
  'work light',
  'jubilee clips',
  'hi vis jacket',
  'sledge hammer',
  'hammerite',
  'rag',
  'skytec',
  'lanyard',
  'drip tray',
  'stanley knife blades',
  'KEN5724470',
  'jigsaw',
  'norbar',
  'headset',
  'RAGS',
  'disposable glove',
  'work bench',
  'ken5822700',
  'screw',
  'calipers',
  'ken5822840',
  'ken5822660',
  'squeegee',
  'puller',
  'ymt5361460',
  'engineers square',
  'roller',
  'polish',
  'radiator',
  'tape measures',
  'tags',
  'dti',
  'blades',
  'combination padlock',
  '13mm spanner',
  'sack truck',
  'harness',
  'oil can',
  'deburring',
  'storage bin',
  'locks',
  'grinding disc',
  'KEN5822700',
  'level',
  'KEN5822590',
  'copper mallet',
  'ear plug',
  'crow bar',
  'marker pen',
  'fire blanket',
  'ken5155740',
  'cups',
  '2022 diary',
  'permanent marker',
  'CR2032',
  'SEN0330600',
  'burr',
  'washers',
  'TORCH',
  'PADLOCK',
  'storage bins',
  'STN5852439A',
  'BRUSH',
  'storage boxes',
  'tape gun',
  'STANLEY KNIFE',
  'KEN5822720',
  'wire wool',
  'bolts',
  'bomber jacket',
  'wood screws',
  '10mm spanner',
  'staple gun',
  'stanley blade',
  'sanding belt',
  'chalk',
  'castors',
  'sockets',
  'ken5185420',
  'cutter',
  'gauntlets',
  'wire brushes',
  'measuring tape',
  'ice',
  'expanding foam',
  'dewalt battery',
  'GREASE GUN',
  'bosch',
  'notice board',
  'DISPOSABLE GLOVES',
  'dust masks',
  'lifting',
  'paint pens',
  'battery charger',
  'sealant gun',
  'numatic',
  'KBE2702024',
  'SAFETY BOOTS',
  'fan',
  'fluke',
  'MASKING TAPE',
  'spray adhesive',
  'ffp2',
  'copier paper',
  'spade',
  'floor scraper',
  'ken5182900',
  'TAPE MEASURE',
  'crowbar',
  'SCISSORS',
  'toilet duck',
  'rake',
  'nitrile glove',
  'araldite',
  'tools',
  'rivets',
  'ken5822910',
  'earplugs',
  'pillar drill',
  'bandsaw blade',
  'SUGAR',
  'scrapper',
  'welding helmet',
  'KEN5587100',
  'thor',
  'loctite 270',
  'ratchet spanner set',
  'marker',
  'string',
  'BATTERIES',
  'nescafe',
  'KEN5582010',
  'shears',
  'm6 tap',
  'wypall',
  'rubber gloves',
  'diary 2022',
  'calendar',
  'KEN5583320',
  'disinfectant',
  'safety goggles',
  'year planner',
  'grinding wheel',
  '19mm spanner',
  'wonder wipes',
  'laminating pouches',
  'cutting fluid',
  'dustbin',
  'spray gun',
  'helmet',
  'impact sockets',
  'HAMMER',
  'yard brush',
  'ken0330500',
  'nail brush',
  'line marker',
  'ken5013120',
  'marker pens',
  'vinyl gloves',
  'buckets',
  'c spanner',
  'coolant',
  'carex',
  'descaler',
  'ken5822720',
  'knives',
  'matlock',
  'castor',
  'spill kits',
  'screw driver',
  'nails',
  'PLIERS',
  'KEN5585020',
  'impact gun',
  'scriber',
  'KEN5822166',
  'yellow paint',
  'leather gloves',
  'sandpaper',
  'air duster',
  'syringe',
  'hi vis fleece',
  'edding',
  'thinners',
  'ansell',
  'measuring jug',
  'paper towel',
  'wheel barrow',
  'mr muscle',
  'trouser',
  'magnetic',
  'gas',
  'pressure gauge',
  'sander',
  'safety',
  'cotton gloves',
  'KEN5010120',
  'trolley jack',
  'ken5728000',
  'cutting oil',
  'tray',
  'straps',
  'jubilee',
  '24mm spanner',
  'cloth tape',
  'body warmer',
  'gorilla glue',
  'barrel pump',
  'impact',
  'inspection light',
  'step ladders',
  'copper grease',
  'compressor',
  'ken5822770',
  'YMT5361460',
  'KEN5725870',
  'KEN5155740',
  'crimp',
  'duracell',
  'distilled water',
  'laptop bag',
  'wood saw',
  'thread repair',
  'mop heads',
  'bench vice',
  'retractable knife',
  'KEN5725900',
  'gauge plate',
  'FFP3',
  'SOCKET SET',
  'antibacterial wipes',
  'combination square',
  'showa',
  'm8 tap',
  'bump caps',
  'silicone spray',
  'pencil',
  'collet',
  'BROOM',
  'cloths',
  'water pump pliers',
  'stamp',
  'anti freeze',
  'nylon hammer',
  'flap wheels',
  'ball pein hammer',
  'KEN5382350',
  'folder',
  'ken',
  'grit bin',
  'step',
  'sds drill',
  'lockout',
  'plastic cups',
  'ken5737140',
  'ken5725870',
  'wheel',
  'needle file',
  'paint tray',
  'rechargeable torch',
  'label printer',
  'boot',
  '2" paint brush',
  'KEN5728000',
  'first aid kits',
  'brother',
  'glue gun',
  'respirator',
  'KEN5188720',
  'spring',
  'KEN5182900',
  'tyre inflator',
  'envelopes',
  'sen5940580k',
  'cargo trousers',
  'bearing puller',
  'stanley knives',
  'disposable face masks',
  'screen',
  'heat shrink',
  'cleaning',
  'bolt',
  'ear defender',
  'belt sander',
  'hylomar',
  'KEN5582110',
  'cloth',
  'noga',
  'strap',
  'headtorch',
  'bin liner',
  'Gloves',
  'wireless keyboard',
  'air',
  'gojo',
  'ken5185380',
  'dishwasher tablets',
  'KEN5823990',
  'knife blades',
  't bar',
  'diaries',
  'filler',
  'post it notes',
  'hard hats',
  'impact socket set',
  'trowel',
  'wire',
  'loctite 638',
  'makita battery',
  'work boots',
  'LR44',
  'DE ICER',
  'KEN5912180',
  'wire strippers',
  'kbe2703300',
  'ken5582120',
  'disposable nitrile gloves',
  'BLEACH',
  'hammers',
  'tig gloves',
  'mig wire',
  'cut resistant gloves',
  'watering can',
  'BLUE ROLL',
  'wellington',
  'contact cleaner',
  'inspection mirror',
  'drill chuck',
  'hose clip',
  'engraver',
  'SCRAPER',
  'pipe bender',
  'threaded rod',
  'ken5405400',
  '3M',
  'tool cabinet',
  'cotton buds',
  'deionised water',
  'crimping tool',
  'multi tool',
  'KEN5822160',
  'ball pein',
  'highlighters',
  'magnetic tape',
  'clear tape',
  'post it',
  'podger',
  'wire stripper',
  'ice pack',
  'brooms',
  'surgical masks',
  'hand tools',
  'ground flat',
  'sand paper',
  'blue nitrile gloves',
  'oil pump',
  'jigsaw blades',
  'LATEX GLOVES',
  'air compressor',
  'highlighter',
  'toggle clamp',
  'scoop',
  'sanding disc',
  'cutlery',
  'bacho',
  'BOOTS',
  'telescopic mirror',
  'threaded bar',
  'side cutter',
  'KEN5737140',
  'wheels',
  'ALLEN KEY',
  'ken5010080',
  'workbench',
  'KEN5822910',
  'dustpan and brush',
  'honeywell',
  'silicone gun',
  'washing up',
  'door closer',
  'rotabroach',
  'punches',
  'HACKSAW',
  'mitutoyo',
  'makita drill',
  'KEN5150500',
  'KEN5185380',
  'socket sets',
  'cones',
  '1/2 ratchet',
  'kbe2702024',
  'sealey',
  'KEN5693000',
  'combination lock',
  'laces',
  'duster',
  'torx set',
  'workwear',
  'centre drill',
  'shredder',
  'TAPE',
  'scribe',
  'chisel set',
  'AA',
  'henry hoover',
  'ken5822590',
  'document holder',
  'angle finder',
  'barriers',
  'thor hammer',
  'Hammer',
  'refuse sacks',
  'jizer',
  'KEN5011120',
  'packaging tape',
  'safety trainer',
  'shoe',
  'ken5010120',
  'brogue',
  'metal bin',
  'engine oil',
  'plier',
  'KEN5587200',
  'multitool',
  'disposable masks',
  'clip board',
  'HEATER',
  'rubber',
  'junior hacksaw',
  'water hose',
  'hand towel',
  'FIRST AID',
  'sticky notes',
  'knife blade',
  'dowel pin',
  'grinding discs',
  'martor',
  'rustoleum',
  'broom handle',
  'storage cabinet',
  'ad blue',
  'sealant',
  'polyco',
  'purell',
  'hi-vis',
  'nitrile disposable gloves',
  'blue rolls',
  'grease nipple',
  '17mm spanner',
  'paper roll',
  'grips',
  'scotch',
  'spill pads',
  'matting',
  'CABLE TIE',
  'Kennedy',
  'tool set',
  'cold chisel',
  'eye wash station',
  '1/2" ratchet',
  'abrasive',
  'cutting compound',
  'eye bolt',
  'saw blade',
  'slings',
  'pcl',
  'bungee',
  'CUTTING DISC',
  'strap wrench',
  'dickies',
  'tool case',
  'boot laces',
  'laminating',
  'A4 paper',
  'dr martens',
  'gauntlet',
  'AC90',
  'tarp',
  'EAR DEFENDERS',
  'nuts',
  'bit set',
  'saw blades',
  '110v transformer',
  'drill sets',
  'clipboards',
  'die nut',
  'wheelbarrow',
  'craft knife',
  'yamoto',
  'rack',
  'sanding discs',
  'punched pockets',
  'SPANNER',
  'nut spinner',
  '5mm drill',
  'notepad',
  'irwin',
  'WIRE BRUSH',
  'TROUSERS',
  'molykote',
  'BRAKE CLEANER',
  'hi viz vest',
  'EAR PLUGS',
  'router',
  'water pump',
  'grub screws',
  'tie wraps',
  'combination spanner set',
  'letter tray',
  'lathe',
  'disposable face mask',
  'AAA batteries',
  'sponges',
  'TORQUE WRENCH',
  'a3 paper',
  'KEN5822670',
  'mop handle',
  'vice grips',
  'sds',
  'antifreeze',
  'mats',
  'cable reel',
  '36mm spanner',
  'KEN5188750',
  'ken5822160',
  'dust pan and brush',
  'arbor',
  'KEN6022800',
  'screwdriver sets',
  'WD-40',
  'latex',
  'ken5823990',
  'wall clock',
  'copper slip',
  'electric heater',
  'ken5587170',
  'extension reel',
  'magnetic tray',
  'snood',
  'ken6012140',
  'KEN5585100',
  'ken5839186',
  'screen wipes',
  'black spray paint',
  'cage',
  'ken5361750',
  'adhesive',
  'chuck key',
  'SPANNER SET',
  'ratchet spanners',
  'ken5822970',
  'york',
  '17mm socket',
  'm8 washer',
  'orbital sander',
  'ken5586570',
  'gun',
  'safe',
  'clear silicone',
  'oxd3312260',
  'spray grease',
  'senator',
  'lights',
  'hex socket',
  'castrol',
  'digital calipers',
  'AAA BATTERIES',
  'bin bag',
  'folding knife',
  'tool',
  'hydraulic oil',
  'clips',
  'KEN5185460',
  'press',
  'washing powder',
  'steel ruler',
  'tweezers',
  'cap head',
  'cable cutter',
  'KEN5370740',
  '19mm socket',
  'KEN5403100',
  'heat resistant gloves',
  'KEN5822970',
  'feeler',
  'trainers',
  'air tools',
  'KEN5410480',
  'ken5585020',
  'nylon mallet',
  'KEN5057160',
  'ALLEN KEY SET',
  'ken5255760',
  'sanding',
  'soap dispenser',
  'key box',
  'floor mat',
  '24mm socket',
  'cabinets',
  'deburr',
  'BATTERY',
  'starrett',
  'fire exit',
  'coat hook',
  'ken5723700',
  'over glasses',
  'dormer',
  'tool boxes',
  'rubber bands',
  'sanding belts',
  't40',
  '3m tape',
  'gaffa tape',
  'uvex boots',
  'crimper',
  'hi viz jacket',
  'ken5826796',
  'ken5822960',
  'pad lock',
  'ear protection',
  'ken5586550',
  'KEN5585180',
  'metal bucket',
  'KEN5823974',
  'ken5839080',
  'janitol',
  'boiler suit',
  'shovels',
  'wood glue',
  'filter',
  'surface cleaner',
  'LOCTITE',
  'TOILET ROLL',
  'dremmel',
  'tyre',
  'Milwaukee',
  'safety knives',
  '1" paint brush',
  'yorkshire tea',
  'counter sink',
  'screwdriver bits',
  'socks',
  'staple',
  'anti slip',
  'ken5259460',
  'contact adhesive',
  'circlip plier',
  'kennedy hand tools',
  'taps and die sets',
  'left handed screwdriver',
  'irwin record vice',
  'industrial tools catalogue',
  'engineers metal files',
  'kennedy professional tool chest',
  'mole grip',
  'battery powered air fed respirator',
  'snap on socket set',
  'drill bit sets',
  'performance power 18v battery',
  'record vice jaws no',
  'digital vernier calipers',
  'shim steel pack',
  'tap and die set',
  'replacement carbon brushes for power tools',
  '3m scotch brite hand pads',
  'rivet nut tool',
  'stanley yankee screwdriver',
  'compressed air line fittings push fit',
  'second hand power tools',
  'sheet metal tools hand tools',
  'digital caliper mitutoyo',
  'tungsten carbide rotary burr',
  'helicoil kits',
  '3m scotch brite wheel',
  'm16 tap',
  'dust extraction sanders',
  '6mm push fit pneumatic connector',
  'hand engraving tools for metal',
  'bench vice for sale',
  'combination square set',
  'metric drill and tap set',
  'air fed mask',
  'hardened steel dowel pins',
  'needle gun',
  'moore and wright engineers square',
  'stud extractor',
  'used power tools for sale',
  'replacement vice jaws',
  'uvex safety shoes',
  'performance power battery',
  'kennedy tool chest',
  'hex bit sockets',
  '1 bsp tap',
  '36mm socket',
  'feeler gauges',
  'lathe cutting tools',
  'vernier callipers',
  'stainless steel pipe cutter',
  'carbide drill bits for sale',
  'pillar drill used drills',
  'stanley yankee screwdriver bits',
  'Dewalt',
  'toolbox on wheels',
  'bench grinder wheels',
  'spade handles wooden',
  'pin c spanner',
  'whitworth socket set',
  'metal tool box',
  'angle grinder storage case',
  'helicoil insert',
  'wanner grease gun',
  'osaki mini metalworking lathe',
  'precision straight edge',
  'air blow guns',
  'countersink set',
  'tool rolls',
  'jacobs chuck taper',
  'dti gauge',
  'thin spanner set spanners',
  'ba screws and nuts',
  'engineers stainless steel rule',
  'parts washer',
  'torque spanner wrench',
  'bondhus hex keys',
  '1 2 bsp tap',
  '50mm flat wood bit',
  'self tapping water barrel tap',
  'vernier digital',
  't nuts',
  'left hand thread die',
  'rivet nut',
  'stanley no 4 plane',
  'hss tap and die set metric',
  'tapered pins',
  'double plasterboard fixing',
  'm14 bolts',
  'countersink bits',
  'power craft drill',
  'torque wrench 1/2"',
  'dormer hss jobber drills',
  'Tool chest',
  'steel rivets',
  'cotter pin',
  '12mm push fit connectors',
  'drill chuck key sizes',
  'whitworth spanners',
  'food safe grease',
  '1 nm torque wrench',
  'air needle scaler',
  'snap on spanners for sale',
  'ffp3 dust mask',
  'variable speed grinders',
  'long hex keys',
  'green silicon carbide grinding wheel',
  'weller soldering iron',
  'mitre saw',
  'welder inverter',
  'pin spanner',
  'right angle spanner',
  '8mm push fittings nylon',
  'linisher for sale',
  'brazing rod flux',
  'dewalt impact wrench',
  'bandsaw',
  'snap on torque wrenches',
  'm12 tapered thread tap',
  'socket set 1/2',
  'digital micrometer',
  'used bench drill drills',
  'fire retardant coverall',
  'bosch 14.4 v battery charger',
  'bosch gbh 24v battery charger',
  'open ended torque wrench',
  '1/4 bspt tap',
  'bosch 12v battery',
  'metric tap and die set hss',
  '36mm spanners',
  'disposable coveralls',
  'long handled shovel',
  'grinding wheel dresser',
  'replacement dewalt 18v batteries',
  'rotabroach cutters',
  'Socket set',
  'jalas safety boots',
  'adjustable pin spanner wrench',
  'morse taper drill chuck',
  'record no 6 vice',
  '400g grease cartridge',
  'm24 tap',
  'cantilever tool box',
  'digital level',
  'esd safety shoes',
  'metal cutting disc for chop saw',
  'tapping drill',
  'torque wrench with calibration certificate',
  'heavy duty wheeled tool box',
  'steel strapping',
  'welding clamps',
  'engineers blue',
  'terry spring clips',
  'kennedy tool catalogue',
  'table saw',
  'lathe tools',
  'replacement socket set cases',
  'anti vibration gloves',
  'engineering measuring tools',
  'Makita',
  '1/4 drive socket set',
  'edge finder',
  'lapping paste',
  'honing tool',
  '3m scotch brite abrasive discs',
  'circlip plier set',
  'pencil grinder',
  'rotary wire brushes',
  'Tool box',
  'height gauge',
  'safety nozzle air blow gun',
  'screw extractors',
  'taps for threading stainless steel',
  'whs trowels',
  'blue roll dispensers',
  'bench grinder guards',
  'drill vice for sale',
  '3m respirator filters',
  'digital micrometer set',
  'engineers level',
  'propane gas torch',
  'professional tool set',
  'helicoil thread repair kits',
  'needle file set',
  'magnetic drill',
  'perf safety boots',
  'bosch keyless drill chuck',
  'metal repair filler',
  'pillar drill chuck',
  'stainless steel shim',
  'grease nipples',
  'high temperature epoxy',
  'hss drill bits long set',
  'allen keys metric',
  'bench drill stand',
  'dial test indicator',
  'sykes pickavant puller',
  'eclipse 66 saw blade',
  'linisher belt',
  'mitutoyo dti gauge',
  'pressure sprayer',
  'sds chuck',
  'shim steel',
  'silver solder',
  '150mm hook and loop sanding discs',
  '3 4 inch drive socket set',
  'carbide burr',
  'screwdriver bit set',
  'workbench drawers',
  'pro performance power tools',
  'norbar torque wrench price',
  'Boots',
  'copper to copper brazing rods',
  'radius lathe cutting tool',
  '1 bsp die nut',
  'milling machine coolant',
  'milwaukee impact wrench',
  'nail gun',
  'Dremel',
  'Safety boots',
  'thread gauges',
  'Vice',
  'bosch cordless drill batteries',
  'hole punch tool',
  '46mm impact socket',
  'cordless drills',
  'hand tools sheffield',
  'bosch sander pads',
  'carbide drill bits',
  'metric fine taps',
  'sheet metal cutter hand tool',
  '3 4 to 1 2 reducer',
  'dewalt grinder case',
  't bolt clamps',
  'aluminium brazing rods',
  'fans',
  'wire wheels',
  'bench drill',
  'magnetic pick up',
  'polyco touchstone 753',
  'weller soldering iron tips replacement',
  '3m face masks',
  'fume extractors',
  'rohm drill chucks',
  'bott cabinets',
  'insert thread reducer',
  'kennedy letter and number punch set',
  'barrier cream for hands',
  'creusen bench grinder grinders',
  'engineers flat hand scraper',
  'loc line coolant hoses',
  'zeus book',
  'bott perfo panels',
  'nitrile disp glove',
  'slip gauges',
  'g clamps',
  'mig welder',
  'senator quality tooling',
  'tig welding gloves',
  'tungsten carbide cutting tools',
  '1 4 drive 12 point af sockets',
  'aluminium oxide grinding wheels',
  '125mm sanding disc',
  'air torque wrench',
  'hex and torx socket set',
  'slide hammer bearing puller',
  'soft jaws',
  '22mm hex bit socket',
  'Knipex',
  'york abrasives products',
  'dickies boiler suit',
  'hickory axe handles',
  'hose clamps',
  'kennedy professional tools',
  't handled hexagon keys',
  '3m roloc surface conditioning disc',
  'dormer drills',
  'Uvex',
  'rust inhibitor spray',
  'slitting saw',
  'thermal arc inverter welder',
  '6mm router bit set',
  'hose pinch clamp',
  'sievi safety shoes',
  'ansell touch n tuff nitrile gloves',
  'socket head shoulder screws',
  'circular saw',
  'elliott lucas pliers',
  'internal micrometers',
  'linisher',
  '3/4 drive ratchet',
  '8mm pneumatic fittings',
  'adjustable spanner set',
  'banding strap',
  'mitutoyo caliper',
  'oil spill granules',
  'pillar drill table',
  'af spanners',
  'toolboxes',
  '14mm hex socket',
  '9 16 af socket 1 2',
  'digital depth gauge',
  'sheet metal punch',
  'ball nose milling cutters',
  'fluke multimeter for sale',
  'rip saw blades',
  'socket set 1/2"',
  '3 jaw lathe chuck',
  'chipping hammer',
  'mag drill',
  'Torque wrench',
  'grinding stones',
  'jewelers loupe 10x',
  'sandvik tools catalogue',
  'tool bags',
  'tool foam inserts',
  'truckers safety boots',
  '27mm nut splitter',
  '46mm spanner',
  'catalogue',
  'torx screws',
  'chop saw',
  'hss drill bits',
  'kennedy socket set price',
  'sievert heating torches',
  'starter tool kit for mechanics',
  '300mm vernier caliper',
  'dormer m4 thread tap',
  'hickory hammer shaft',
  'kennedy wheeled tool case',
  'nilfisk alto pressure washers',
  'oxygen welding cylinder',
  'sherwood drill bits',
  '6v rechargeable lantern batteries and charger',
  'bosch heat gun',
  'crowfoot',
  'mitutoyo 200mm vernier',
  'parallel pin punch',
  'snap on screwdriver set',
  '1 8 npt tap',
  'anti fatigue mat',
  'bandsaws',
  'noga hand deburring tool',
  '3/8 socket set',
  'heavy duty deep throat g clamps',
  'm10 die',
  'smoothrite paint colours',
  'kennedy engineering tool kit',
  'stainless steel soldering flux',
  '110v extension',
  '3m hook and loop sanding discs',
  'heavy duty electric extension cable',
  'knurling tool',
  'plastic tool chest with drawers',
  't slot clamps',
  'air die grinder',
  'double acting cylinders',
  'heavy duty rivet gun',
  'helicoil taps',
  'lift tables',
  'tapered reamers',
  'torx screwdrivers set',
  'welding rods',
  'tab washers',
  '10mm socket',
  '200mm grinding wheel',
  'af hex socket',
  'cordless drill 18v 13mm chuck',
  'pry bar set',
  'shims stainless steel',
  'taper hand reamer',
  'tarpaulins',
  'yamoto tool chest',
  '8mm steel dowel pins',
  'eye shield for bench grinder',
  'french chalk',
  'slot drill',
  'Wheelbarrow',
  'countersinks',
  'hex security bit',
  'high temperature ptfe grease',
  'copper working tools',
  'electrician tool bags',
  'hermes sanding discs',
  'sander backing pad',
  'tool storage',
  'welding gauntlets',
  'carver clamps',
  'precision screwdriver set',
  'sledge hammer handles',
  'vee block and clamp',
  'dickies trousers',
  'hydraulic puller ram',
  '32mm socket',
  'milling machine vice milling',
  'wood drill bits',
  '1/2" ratchet handle',
  'bolt extractor',
  'crowfoot wrench',
  'fire and heat resistant gloves',
  'fret saw blades for wood',
  'hitachi battery charger',
  'reciprocating saw blades',
  'sia abrasive',
  'steel hole punch',
  'wire brush for drill',
  'brass machine screws',
  'c clamps',
  'chicago pneumatic',
  'kennedy socket set',
  'thread cleaning tool',
  '1 4 drive hex bit adaptor',
  'air hose reels',
  'hickory pick axe handles',
  'metric tap set',
  'nut splitter',
  'toolbox with tools included',
  'bore gauge set',
  'csk rivets',
  'dead blow hammer',
  'die grinder bits',
  'gasket cutter',
  'bearing puller kit',
  'box spanner',
  'c spanner sizes',
  'gas brazing torch',
  'sheet metal nibbler',
  'wd40 5ltr',
  '1 4 schrader fittings',
  '10mm hole punch',
  'digital depth micrometer',
  'imperial allen keys',
  'Square',
  '32 mm masonry drill bit',
  'bahco adjustable spanners',
  'dovetail saw',
  'file handle',
  'perfo',
  '19mm hex socket',
  'argon gas regulator',
  'cofra safety boots',
  'cutting paste for drilling',
  'magnetic base',
  'safety signs',
  'sash clamp',
  'solid carbide countersinks',
  'uv protection face shield',
  'air line hose',
  'bit adaptor 1 4 hex to 1 4 square',
  'er32 collet chuck',
  'hand drill',
  'rolling toolbox',
  'uvex safety boots',
  'crawford collets',
  'hydraulic press',
  'scythe',
  't50 torx bit',
  'torque wrench 3/8',
  '6mm hex socket 1 2 drive',
  '6mm push fit straight connector',
  'bearing puller separators',
  'm8 tap set',
  'strimmer',
  'welding screen',
  'a4 copying paper',
  'counter',
  'garden hose',
  'thread gauge',
  'blacksmith drill',
  'bsp grease nipples',
  'engineers 6 inch 150mm steel rule',
  'high tensile socket head cap screws',
  '3 4 drive extension bar',
  'angle grinder accessories',
  'Evo-Stik Gripfill',
  'flat blade screwdriver',
  'hex socket set',
  'internal bore micrometers',
  'lathe chuck soft jaws',
  'm16 t nuts',
  'pedestal grinder',
  'polishing mop for grinder',
  'record hand plane',
  'slip stones sharpening',
  'table folding legs',
  '21mm ring spanner',
  '60 deg hss countersink tool',
  'BOSTIK ALL PURPOSE',
  'EVO-STIK MULTI-PURPOSE TIMEBOND',
  'hand pump',
  'ignition timing light',
  'knife retractable',
  'kobe air riveters',
  'MULTI-PURPOSE TIMEBOND',
  'Safety trainers',
  'torque screwdriver set',
  '3m 6000 full face respirator',
  'brake pipe spanner set',
  'cutting disc 115mm',
  'hex to square drive adaptor',
  'calibration block gauge',
  'Fan',
  'heavy duty centre punch',
  'left hand taps',
  'tool chest lock',
  'battery drill',
  'Clamps',
  'end mill',
  'fluke multimeter test leads',
  'gauge blocks',
  'half saddle clamp',
  'internal groove tool',
  'kennedy professional spanners',
  'laser level',
  'stainless steel arc welding electrodes',
  'trolley jacks',
  'bandsaw blades',
  'cut metal sheet shears',
  'gas soldering iron',
  'helicoil kit',
  'letter steel stencils',
  'scribers',
  '1 4 router bit set router bits',
  '150mm polishing pads',
  '50mm grinding disc',
  '600 nm torque wrench',
  'facom ratchet',
  'lint free rags',
  'parallels',
  'service engineers tool case',
  'taper reamer sizes',
  '3/4 socket set',
  '3/8 ratchet',
  'cobalt drill set',
  'ear plug dispenser',
  'impact driver bits',
  'sack barrow',
  'small cordless drill driver',
  'spot face cutter',
  'st steel p clips',
  '1 2 inch drive socket set',
  '19mm deep impact socket',
  'BoschT2Promo',
  'pop rivet gun',
  'silver solder fluxes',
  'stainless steel cutting saws',
  'tacwise',
  'Wera',
  'bolt cutters',
  'breaker bar 1/2" square drive',
  'flame retardant trousers',
  'hydraulic pipe spanners',
  'kennedy ratchet spanners',
  'm16 rawl bolts',
  'magnifying glass',
  'angle plate',
  'cable cutters',
  'laser measure',
  'm10 washer',
  'metric lathe thread cutting tool',
  'radius gauges',
  'stilsons',
  '24mm combination spanner',
  'carpenters t square',
  'paint brush set',
  'pin wrench',
  'tape measure 5m',
  'thread file',
  'desk fan',
  'dowels',
  'Drill',
  'impact sockets 1 2 drive',
  'm12 tap',
  'metal soluble cutting oil',
  'pipe flaring tool',
  'polishing bench grinder',
  'sharpening stone',
  'snap on tool box',
  '1 4 inch npt air hose',
  'depth gauge',
  'hand mitre saw',
  'm8 hand screw',
  't bar socket spanners',
  'tapered end mills',
  'ball joint splitter',
  'inspection magnifying glass',
  'large tool bags heavy duty',
  'drawer dividers',
  'metric tapping sets',
  'micrometer 0-25mm',
  'pick set',
  'thor hammer copper copper size a',
  'torque wrench 300 nm',
  'AEA961',
  'bore gauge',
  'Disposable gloves',
  'full face respirator',
  'm10 rivet nuts',
  'murex welding rods',
  'Tool bag',
  '19mm ratchet spanner',
  'electrical screwdrivers',
  'milling machine',
  'o ring kit',
  'Pliers',
  'rechargeable led work light',
  'service engineers tool kits',
  'slide hammer',
  'unbrako hexagon keys',
  '16mm chuck drills',
  'bowers bore micrometer',
  'drum opener',
  'floor fan',
  'kennedy 1 2 drive socket set',
  'rivet nut insertion tool',
  'torx screwdriver set',
  'wiha screwdriver set',
  'yamoto socket set',
  '5 16 hex insert bit',
  'Drill bits',
  'hinge',
  'hitachi angle grinders',
  'industrial drain plunger',
  'insulated screwdriver set',
  'magnetic sweeper',
  'rotary burr',
  'socket adaptor 1 4 to 3 8',
  'Spanner set',
  'stainless steel spanners',
  'tool rest for bench grinder',
  'watchmakers screwdrivers set',
  '22mm spanner wrench',
  'broken tap remover',
  'Facom',
  'rockwell hardness tester',
  'welding earth clamp',
  '50mm deep socket',
  '6.8mm hss drill bits',
  'banding machine',
  'dial indicator torque wrench',
  'dial test indicator spares',
  'engineers reference book',
  'engineers vice for sale',
  'Kennametal',
  'Loctite',
  'makita impact wrench',
  'small parts storage',
  'tap sets',
  'whitney punch',
  'wooden file handles',
  '1 5 nm torque wrench',
  '25mm socket 1 2 drive',
  'Bahco',
  'face mill cutter',
  'facom ratchet spanners',
  'hitachi cordless screwdriver',
  'hose clip pliers',
  'm5 tap set',
  'socket set 1/4',
  'stillson',
  'bearing press',
  'blue engineers marking',
  'bott perfo hooks',
  'circular saw blades',
  'dewalt tools',
  'hi vis vests',
  'kennedy hex key set',
  'parts cabinet drawers',
  'Polyco Granite 5 Beta Leather Cut Resistant Gloves 891',
  '5m tape measure',
  'bullfinch gas torch',
  'digital height gauge 600mm',
  'hydraulic brake pipe flaring tool',
  'imperial spanner set',
  'performance pillar drill',
  'pillar drill chuck guards',
  'pin punch set',
  'Safety shoes',
  't30 torx bit screwdriver',
  'torque spanner set',
  '6mm hole punch',
  'ball ended hex driver',
  'duck oil',
  'miniature spanners',
  'self tapping screws',
  'stainless steel cutting disc',
  '15mm hex',
  'bench grinder stand',
  'impact socket retaining pin',
  'm10 t nuts',
  'plumbing box spanners',
  'shim steel roll',
  'short torque wrench',
  'straight edge',
  'chemical resistant visor',
  'collet chuck lathe',
  'hex bit driver set',
  'industrial chop saw',
  'open ended ratchet spanner',
  '3m deburring wheels',
  '55mm open end ring spanner',
  'disposable gas bottle regulator hose',
  'flat drill bit',
  'mop and bucket',
  'round file',
  'stone cutting discs',
  'telescopic inspection mirror',
  'Toolbox',
  'cofra',
  'gear puller tool',
  'pad saw blades',
  'rustoleum hard hat spray paint',
  '36mm 1 2 drive socket',
  'bosch nicd battery',
  'eye muffs',
  'flame retardent overalls',
  'flare nut spanner',
  'forged steel tools',
  'hasp and staple',
  'kobe air tools',
  'loctite 577',
  'norton sharpening stones',
  'nuts and bolts',
  'springs',
  'square head wrench',
  'weedkiller',
  '1/2 socket set',
  'blue cotton boiler suit',
  'bosch-cordless-18v',
  'carver clamps price',
  'citrus based adhesive remover',
  'counterbore',
  'die set',
  'food grade silicone lubricant',
  'harris scraper blades',
  'makita battery batteries chargers',
  'performance power drill battery 18v',
  'pliers set',
  'Socket Head Shoulder Screws',
  'womens safety shoes',
  'adjustable c spanner',
  'air tool oil',
  'cobalt drill bits',
  'cordless grinder',
  'end mill 6mm shank',
  'Face_Coverings',
  'hermes abrasive rolls',
  'jugs',
  'lin bin',
  'needle files',
  'sandvik coromant milling inserts',
  'single hex sockets',
  'squeegees',
  'steel engineers square',
  'tyre pressure gauge',
  '3m cubitron grinding disc',
  'bastard files',
  'cordless wrench impact',
  'cylinder honing stones',
  'grinding wheels',
  'guhring drill sets',
  'hand reamer tool',
  'imperial tape measure',
  'karcher pressure washer',
  'kobe die grinder',
  'pcl airline fittings',
  'socket rails clips',
  'thor replacement hammer heads',
  'thread chaser tool',
  '3m scotch weld adhesive',
  '4 jaw chuck',
  'c spanners',
  'Cofra',
  'internal thread chaser',
  't45 torx bit',
  'tool tote tray',
  '110v drill',
  'air belt sander',
  'bsp tap',
  'cleaning station',
  'emery cloth roll',
  'external circlip pliers',
  'indexa indexable tooling spares',
  'irwin vise grips',
  'makita 18v battery',
  'norbar torque wrench',
  'spiral flute tap set',
  '17mm ratchet spanner',
  '7 16 whitworth square socket',
  'alan key set',
  'black caulk',
  'drill bushes',
  'Files',
  'long handle bill hook',
  'machine vice',
  'machine vice handle',
  'milling vice milling',
  'msa helmet',
  'nibbler',
  'pneumatic fittings',
  'slogging spanner',
  'type 5 6 coverall',
  '30mm spanner',
  '30mm spanners',
  '46mm socket',
  'air drill',
  'dremel 4000',
  'engineering vice',
  'hand fret saw',
  'makita 18v lxt dhp458',
  'Mitre saw',
  'power hacksaw',
  'strip and clean discs',
  '150mm backing pad 5 16',
  '8mm hex 1 2 socket',
  'adjustable hole cutter',
  'deburr tool',
  'dormer taps',
  'dowel pins metric',
  'taper drill chuck',
  '10mm tap',
  '12mm hole punch',
  '41mm impact',
  'crimpers',
  'deburrer',
  'digital micrometer mitutoyo',
  'fly killer',
  'magnetic strip',
  'magnetic welding clamp',
  'nilfisk pressure washers',
  'plasma cutter',
  'radius gauge',
  'SocialDistancing20',
  'spanners set',
  'spray guns',
  '3 8 drive torque wrench',
  'air grinder',
  'battery for performance power drill',
  'combination set',
  'deep impact sockets',
  'drill blanks hss',
  'm10 tap',
  'sandvik cutting tips',
  'shadow board',
  'side and face cutters',
  'torque multiplier',
  'waste bins',
  'welder',
  '17mm hex driver',
  'allan key set',
  'circular wire brushes',
  'dickies coveralls short sleeve',
  'generator',
  'metabo',
  'rubber mats',
  'safety footwear',
  'weed killer',
  '12mm hex bit',
  '24mm ratchet spanner',
  '30mm socket',
  'ba socket set',
  'bosch 18v cordless drill price',
  'broom long handle',
  'corner radius milling cutter',
  'heavy duty air chisel',
  'hitachi 18v battery charger',
  'oxford precision measuring equipment',
  'record vice jaws',
  'retractable airline',
  'rothenberger',
  'tap wrench set',
  'tool steel',
  'tyvek coverall',
  'wide jaw wrench',
  'wool polishing bonnets',
  'boring bar',
  'bott workbenches',
  'dewalt impact driver 18v case',
  'draper',
  'gas arc regulators',
  'hand log saw',
  'hi-viz vest',
  'Knife',
  'm5 taps',
  'metal paint kettle',
  'planishing hammer',
  'pry bars',
  'tool box handles',
  'unf taps',
  '20mm end mill',
  '38 mm box spanner',
  'antex soldering iron',
  'bench sanders',
  'deep socket',
  'floor mats',
  'forstner bit',
  'grease guns for sale',
  'hss drill set',
  'pitch fork',
  'power craft products',
  'scraper blades',
  'tool clip',
  'torx bit set',
  'universal square key',
  '13mm hex',
  'angle grinder spanner',
  'broach',
  'carbide 3mm shank end mill',
  'decorators tools',
  'dti stand',
  'ffp3 masks 3m',
  'flat head screwdriver',
  'ground steel parallels',
  'hand knurling tool',
  'replacement torch bulbs',
  'sherwood cutting tools tap and die set',
  'sweeping brushes',
  'thermometers',
  'vernier caliper mitutoyo 300mm',
  'vice jaws',
  'vise grip',
  'waterproof sealant for plastic',
  'wood chisel sets sale',
  'wrecking bar',
  '1 2 air impact wrench',
  '1/4 socket set',
  '11-100',
  '3 4 drive 60mm socket',
  '30mm ball nose cutter',
  '3m scotchbrite rolls',
  '5mm shank router bit',
  'borescopes',
  'burr set',
  'db3dl2 3.6v screwdriver',
  'diamond file set',
  'Lathe',
  'left handed saw',
  'lubricating oil dispensing bottles',
  'm12 t nut',
  'makita spirit level',
  'pin chuck drilling',
  'roller cabinet',
  'slitting saw arbor',
  'small boring bar set',
  'Tap wrench',
  'valve spring compressor',
  'welding curtains',
  'bahco adjustable',
  'benchmark trousers',
  'boring bars',
  'Evolution',
  'grease gun nipples',
  'kennedy tools catalogue',
  'knipex pliers',
  'matlock padlock',
  'ratchet combination spanner set',
  'rothenberger gas torch',
  'slitting saw blade',
  'sprayers',
  'Torch',
  '1 2 square drive socket',
  '1 4 drive socket set',
  '3/8 10mm allen socket',
  'ADCOLA 07418R',
  'bsp taper taps',
  'cobalt countersinks',
  'cobalt drill',
  'cylinder clevis mount',
  'kennedy tool bag',
  'm10 plastic knobs',
  'mops',
  'nut driver set',
  'polo shirt',
  'pulleys',
  'roll pins',
  'skytec gloves',
  'surface plate',
  'tool belt',
  'tool chest liner',
  'wera screwdrivers',
  'wheeled tool boxes',
  '110v grinder',
  'bolt extractor socket',
  'dial gauge',
  'filing cabinet',
  'galvanised drip tray',
  'heat gun nozzles',
  'heavy duty air chisel hammer',
  'latex gloves natural powder free - med. (box-100)',
  'm4 tap',
  'reverse thread tap',
  'rohm revolving centres',
  'socket head cap screws',
  'titex drills',
  'Trolley',
  'tyre pressure gauges',
  'welders',
  'welding curtain',
  '3 8 to 1 4 reducer',
  'crow foot',
  'die',
  'drill press',
  'fox wedge',
  'irwin sash clamps',
  'platform truck',
  'saw for cutting plastic',
  'slip gauge',
  'Spanner',
  'stamps',
  'stanley fatmax',
  'warehouse coats',
  '1 mm parallel pin punch set',
  '30mm countersink',
  '3mm shank carbide burrs',
  '41mm spanners',
  'ffp3 masks',
  'heavy duty blue paper towels',
  'key hangers',
  'lead cutting tools',
  'm5 screw',
  'refractometer',
  'stanley yankee bits',
  'zinc galvanising spray',
  'hook and pick set',
  'magnesium welding rods',
  'metric spanner set',
  'small tool chest',
  'steel rule 300mm',
  'tct drill bits',
  'tyvek',
  '10mm 8mm reducer',
  '10mm hex drive',
  '15mm hex socket',
  '21mm offset ring spanner',
  'Allen keys',
  'barrel taps',
  'bulldog spade',
  'centre finder',
  'depth micrometer',
  'dewalt mitre saw',
  'diamond needle files',
  'elasticated boiler suits',
  'keyless drill chucks',
  'ratchet screwdriver',
  'sds core drill bits',
  'sherwood tools threading set',
  'soldering kit',
  'tap and die',
  'tape measure 8m',
  '1/2 impact socket set',
  '1/4 bsp nut',
  '32mm hex socket',
  'absorbent granules',
  'bearings',
  'bulldog shovels sale',
  'Dti',
  'fingerless gloves',
  'hand reamer',
  'hss countersink set',
  'lathe chuck',
  'loc line',
  'masonry drill bits',
  'mitutoyo dial gauge',
  'molyslip',
  'Nitrile gloves',
  'oil stone',
  'oxy acetylene gauge',
  'Paint',
  'protective mesh sleeving',
  'rotabroach standard cutters',
  'rubber mat',
  'tig welder',
  '1 2 flex head ratchet',
  '10mm reamer',
  '3m radial bristle disc',
  '700bar hydraulic hand pump',
  'Bosch',
  'brass brush',
  'chamfer tool',
  'crows foot',
  'e torx spanners',
  'm6 knurled nut',
  'Reamer',
  'snail brand spanners',
  'storage boxes plastic',
  'tig welding tungsten electrodes',
  'vice soft jaws',
  'welding wire',
  '55mm socket 3/4" dr',
  'bricklaying tools for sale',
  'c clamp',
  'carbon brushes',
  'carter shovels',
  'clarkson collets',
  'cup grinding wheels',
  'Dormer',
  'gas torch',
  'hydraulic bench press',
  'kennedy pry bar',
  'knurled nuts',
  'low tack tape',
  'm6 tap set',
  'moore and wright protractor',
  'pilot drill',
  'propane gas hose',
  'tuffsafe gloves',
  'tweco mig torch',
  '10mm to 8mm thread reducer',
  '35mm spanners',
  '3m backing pads',
  'airline hose',
  'britool',
  'chuck guard',
  'countersink bit',
  'dial indicator',
  'die springs',
  'drill lubricant',
  'enamel spray paint',
  'hitachi circular saw blade',
  'kennedy professional screwdriver set',
  'kennedy tool box',
  'm4 washers',
  'melco box spanner',
  'morse taper arbors',
  'Nail gun',
  'Norbar',
  'nozzle',
  'Pry bar',
  'recipricating saw',
  'ryobi',
  'self tapping screw kits',
  'silicon sealant',
  'thread repair kit',
  'tool kits',
  'tuffsafe safety boots',
  'wheelie bin 240l',
  '19mm socket 3 4 drive',
  '2 mm router slot cutter',
  '40mm forstner bit',
  'af ring spanners',
  'back counterbore tools',
  'blue point tools',
  'bolle safety glasses price',
  'bosch 125mm angle grinder 110v',
  'calipers digital',
  'coolant hose',
  'deburring tool',
  'deburring tool set',
  'DTI',
  'eclipse centre punch',
  'head torches',
  'kennedy mig welding torches',
  'kneeling pad',
  'kobe air tool spares',
  'leak detector spray',
  'm12 anchor bolts',
  'm12 socket screw',
  'm5 tap',
  'magnifying lens 10x',
  'makita backing pads',
  'measuring wheel',
  'o-clip pincers',
  'stools',
  'tenon saws for sale',
  'thread repair kits',
  'wad punch',
  'wesco oil can',
  'air line connector',
  'back spot facing tools',
  'crowfoot spanner',
  'die nut set',
  'hammer shaft wedge',
  'hook spanner',
  'infrared heater elements',
  'irwin clamps',
  'lathe parting off tool',
  'loctite 406',
  'long feeler gauges',
  'number stamps',
  'pin punches',
  'porta power',
  'rutlands tools',
  'scotch brite 3m pads',
  'split pin',
  'torque spanner',
  'used panel beating tools for sale',
  'Winter_Workwear',
  '1 4 bsf grease nipples',
  '17mm impact socket',
  '31 mm spanner',
  '3m double sided tapes',
  '5 16 unf nuts',
  '5mm drill bit',
  'air fittings',
  'band saw',
  'brazing rods',
  'dewalt dcf899p2',
  'drill all drill bit set',
  'gasket',
  'grinding wheel bushes',
  'hss split tap and die set',
  'internal calipers',
  'm14 tap',
  'needle scaler',
  'pipe chain wrench',
  'power tools',
  'saw set tool',
  'soft rubber mallet',
  'submersible pumps',
  'vernier height gauge',
  'britool ratchet 1 2',
  'cone cutter',
  'deb stoko',
  'denso tape',
  'drift',
  'drill and tap set',
  'e12 torx socket',
  'flanged nuts',
  'hole deburring tools hand',
  'kennedy quality industrial tooling',
  'kennedy screwdriver set',
  'lawn mower',
  'Magnet',
  'mechanic tool kit',
  'oxford precision micrometer',
  'ridgid pipe cutter',
  'roloc sanding disc',
  'steel toe cap boots',
  'Table saw',
  'tool box dividers',
  'Welding',
  '6 mm tap',
  'araldite applicator gun',
  'degreaser spray',
  'die grinder collet',
  'f clamps heavy duty',
  'grip seal bags',
  'hardened steel punch set',
  'kennedy combination spanner set',
  'm12 helicoil',
  'makita chuck key',
  'mechanic tool set',
  'oleonix',
  'paint kettle',
  'personal protective equipment',
  'podger bars',
  'rechargable torch',
  'retractable air line',
  'router cutters',
  'saftey glasses',
  'Saw',
  'saw horse',
  'silver steel 12mm',
  'slitting saws',
  'soft jaws 3 jaw chuck',
  'switchable magnetic base',
  'Tool kit',
  'urinal blocks',
  'van vault',
  'wire brush set',
  '1/4 ratchet',
  '100 x 610 sanding belts',
  '37-675',
  'anti seize copper grease',
  'bench drilling machine',
  'cable cover',
  'chain wrench',
  'chemical wellingtons',
  'cleaning rags',
  'coat hooks',
  'cordless screwdriver',
  'dovetail milling cutters',
  'dremel accessories',
  'dust extraction',
  'galvanised gate hooks',
  'kobe tools',
  'pallet trucks',
  'pneumatic',
  'puller kit',
  'raaco',
  'socket set 3/8 metric',
  'spring loaded bolt',
  'step up',
  'surface gauge',
  'surface plates',
  'bosch drill',
  'carbide drill',
  'Die grinder',
  'forstner bits',
  'gedore',
  'gilbow snips',
  'hardness test files',
  'hose clips',
  'kennedy magnetic pick up tool',
  'mounted points grinding wheels',
  'rust remover',
  'safety helmets',
  'sievert',
  'soldering blow torch',
  'vee block',
  'vice grip',
  'welders chipping hammer',
  '1/4" unc tap',
  'beard masks',
  'cupboards',
  'dewalt batteries',
  'dewalt boots',
  'geared pillar drill',
  'heli coil metric thread repair kit',
  'Impact wrench',
  'imperial spanners',
  'indexa',
  'mt2 drill bits',
  'parting off tool',
  'pcl air gun',
  'pressure washer hoses',
  'propane gas torch kit',
  'Rags',
  'safety helmet',
  'slideway oil',
  'spring clamps',
  'studding',
  'torch rechargeable',
  'welding goggles',
  '11-618',
  'air nozzles',
  'bearing',
  'belt laser alignment tool',
  'bosch powertool spares',
  'coventry die box',
  'dewalt 18v battery lithium ion',
  'diamond file',
  'end mill 16mm',
  'engraving pen',
  'large pipe cutter',
  'metal paint',
  'mitutoyo 25 50mm micrometer',
  'paint scrapers',
  'parting tool',
  'plastic dome nut covers',
  'raaco storage systems',
  'router bits',
  'sash clamps heads',
  'sign',
  'stud extractor socket',
  'traffic film remover',
  'welding clamps pliers',
  'wire rope',
  'work gloves',
  '1 4 ratchet spanner',
  '3m sanding pads',
  'block plane blade',
  'bosch grinder',
  'dolly',
  'drum taps',
  'funnel set',
  'hand drill chuck',
  'hex bits',
  'label remover',
  'm12 nuts',
  'm12 studding',
  'machine taps',
  'Mallet',
  'miniature needle nose pliers electronics',
  'pin punch',
  'planer',
  'plastic storage bin',
  'polisher',
  'polishing',
  'Punch',
  'record sash clamp heads',
  'sheet metal hole punch',
  'stahlwille',
  'stanley jack plane no 5',
  'stanley storage systems',
  'stencil letters',
  'telescopic magnet',
  'torx socket set',
  '2 stroke oil',
  '3m ear plugs',
  '3m scotch brite polishing belts',
  'air fresheners',
  'air sander',
  'aluminium welding flux',
  'axle stands',
  'bosch 18v battery charger',
  'butane gas torch',
  'chemical gloves',
  'chisels',
  'coverall disposable',
  'Disposable Gloves, Clear, Vinyl, Powder Free, Size L, Pk-100',
  'drilling machine clamps',
  'eclipse scriber point',
  'garden rakes for sale',
  'hand files',
  'hss slitting saws',
  'hydraulic puller set',
  'kennedy impact socket set',
  'kennedy steel rule',
  'ladies safety shoes',
  'lithium grease',
  'm16 tap wrench',
  'milling machine arbors',
  'moor and wright',
  'o rings',
  'pipe clamp',
  'plastikote',
  'platform',
  'ptfe lubricant',
  'sds wood chisel',
  'speedglas',
  'Tegera 9126',
  'tool board',
  'Vernier',
  '100mm adjustable spanner',
  '50ml bottles Loctite 603',
  'air chisel',
  'air regulator',
  'boring head',
  'Brush',
  'buy kerbing tools',
  'Clamp',
  'electrical screwdriver sets',
  'excel pillar drills',
  'eye bolts',
  'face visor',
  'garden border fork',
  'heavy duty scraper',
  'helicoil installation kit',
  'helicoil tapping sizes',
  'hex bit set',
  'holesaws',
  'Hose',
  'hose connector',
  'kennedy circlip pliers',
  'kennedy spanner set',
  'knee pads inserts',
  'loctite 242',
  'machine clamps',
  'matlock storage bins',
  'Micrometer',
  'mitutoyo thread micrometer anvils',
  'Ratchet',
  'ripper milling cutters',
  'Screwdriver set',
  'scroll saw',
  'soldering',
  'spax wood screws',
  'Trousers',
  '1 mm welding wire',
  '1/2 drive hex',
  '14mm allen key',
  '3 8 drill chuck',
  '32 50 mm spanner set',
  '8mm box spanner',
  'center punch',
  'cold chisel set',
  'combi drill',
  'continental drive belts',
  'copper pipe benders for sale',
  'diamond files',
  'dremel multi tool',
  'dronco cutting discs',
  'GL890',
  'hss hacksaw blades',
  'kennedy tool box parts',
  'keysteel',
  'kobe drill',
  'low cracking pressure check valve',
  'm12 rawl bolts',
  'orbit sander',
  'organiser',
  'oxy acetylene hose',
  'r clip',
  'rivnut tool',
  'Sander',
  'senator tools',
  'Sprayer',
  'steel banding',
  'tegera gloves',
  'thor hammer mallet',
  'Tool cabinet',
  'wiha',
  '13mm socket',
  '22mm wrench',
  '28mm extended socket',
  'allen keys imperial',
  'drill vice',
  'emery tape',
  'file handles',
  'hacksaw blades 12 inch',
  'high temperature silicone grease',
  'hinges',
  'hitachi cordless drill drivers',
  'jallatte safety boots',
  'matte black spray paint',
  'nut spinners',
  'osaki power tools',
  'overshoes',
  'plane blades stanley',
  'pryor letter stamps',
  'Puma',
  'right angle chuck drill',
  'Roll cab',
  'Screwdriver',
  'shorts',
  't6 torx',
  'Tegera 9185',
  'trolly',
  'Uvex safety shoes',
  'welding jacket',
  '12 nm torque wrench',
  '3 8 socket extension',
  '48mm socket 1 2',
  'air blow gun',
  'bsp 1 8',
  'diamond core drills',
  'drain cleaner',
  'dust pan and brushes',
  'feeler guage',
  'files for stainless steel',
  'flexible socket extension bar',
  'foam gun',
  'Heat Gun Nozzles',
  'hi vis clothing',
  'hoist',
  'kennedy hammer',
  'locking pliers',
  'microfibre cloths',
  'Mitutoyo',
  'Overalls',
  'panel beating dolly',
  'protractor combination square set',
  'reduced shank end mills',
  'rotary wire brush',
  'Scissors',
  'screwdriver bit handle',
  'Snap on',
  'Socket sets',
  'soluble oil coolant',
  'spanner sets',
  'stanley tool box',
  'Tape measure',
  'tyre inflator connector',
  'utility knife',
  'yellow floor marking tape',
  '1/2" socket set',
  '10mm hex key bit',
  '10mm pipe bender',
  '4 in 1 reversible ratchet spanner',
  '8mm hex 1 4 drive socket',
  'air polisher',
  'castor wheels',
  'de ionised water',
  'dealer boots',
  'dewalt grinder',
  'ep2 grease',
  'facom spanner set',
  'GL818',
  'leather nail pouch',
  'lighting',
  'micrometer set',
  'office chairs',
  'platform trolley',
  'polishing compound',
  'rivnut',
  'scotch brite surface conditioning discs',
  'scraper set',
  'seal removal tool',
  'stanley fatmax screwdriver',
  'step stool',
  't slot milling cutters',
  'tachometer',
  'turtleskin',
  'Uvex boots',
  'welding magnet',
  'wheelie bins',
  '1 2 ratchet handle',
  '10mm 1 4 drive socket',
  '3 4 drive torque multiplier',
  '32mm combination spanner',
  '3m half mask filters',
  '3m versaflo',
  '5mm tap',
  '8mm socket',
  'compressed air',
  'drawer dividers tools',
  'eclipse plus 30 hacksaw blades',
  'engineers scrapers',
  'engineers vice',
  'eyebolt',
  'gloves vinyl',
  'honeywell airvisor 2',
  'kennedy torque wrench',
  'lab coat',
  'locktite',
  'marigold PX140',
  'metal cutting shears',
  'oil free air compressor',
  'plastic shovels for sale',
  'pneumatic air engraver',
  'polyco jet black',
  'rachet spanners',
  'reamers',
  'riveter',
  'sanding blocks',
  'SILVER STEEL',
  'spline bit',
  'storage case',
  'torq x tools',
  '12 point 12mm socket',
  '3 8 sq drive 3 4 af socket',
  'anti spatter spray',
  'battery tester',
  'bulldog',
  'bunding',
  'chalk line',
  'collet chuck',
  'crimping kits',
  'Drill bit set',
  'Grease gun',
  'heat gloves',
  'Helicoil',
  'helicoil inserts',
  'jacobs chuck arbors',
  'Kobe',
  'Ladders',
  'm3 tap',
  'mirka',
  'moldex ffp3',
  'plastic bags',
  'plastic tip screwdriver set',
  'q max cutter',
  'qualfast socket head cap screws',
  'roloc 50mm',
  'rounded nut socket remover',
  'safety gloves',
  'sleeve',
  'spade shafts',
  'stanley measure tape',
  'sykes pickavant hydraulic puller kit',
  'tube cleaning brush',
  'two part methacrylate adhesive',
  'v block',
  'wood chisels',
  '11-840',
  '12 14 tpi hacksaw blades',
  '25mm masonry drill',
  'air powered pencil grinder',
  'ansell 37-501',
  'combination flex head ratchet spanner',
  'de burr',
  'devcon',
  'duct tape for sale',
  'fuel can',
  'grinding',
  'hoe',
  'irwin tool bag',
  'iso boring bars',
  'kennametal',
  'm20 tap',
  'mounted points',
  'multi tool blades',
  'plastikote spray paint',
  'POLYCO CAPILEX',
  'Polyco Nemesis',
  'record bolt cutters',
  'right angle drill',
  'sandvik',
  'Screws',
  'snap on 3 8 torque wrench',
  'socket adapter',
  'socket rail',
  'stainless steel wire brush',
  'tegera 295',
  'torque screwdriver',
  'trolley wheels',
  '10mm ratchet spanner',
  '13mm ratchet spanner',
  '2 mm router bit',
  '500cc grease cartridges',
  '75mm sanding discs',
  'boiler suits',
  'bosch sanding discs',
  'Bott',
  'burns kit',
  'centre punch set',
  'coshh cabinet',
  'dickies overalls',
  'drill guard',
  'face mill',
  'Ffp3',
  'File',
  'filtermist',
  'flux',
  'footwear',
  'garden shears',
  'gorilla',
  'hack saw',
  'half round file',
  'hand stamp',
  'Impact driver',
  'imperial sockets',
  'kevlar gloves',
  'left hand drill',
  'mole grip set',
  'ND45 N-Dura 45 Green Nitrile Gloves',
  'norbar 3 4 torque wrench',
  'office desk',
  'open ended ring spanners',
  'piston ring pliers',
  'polisher kit',
  'Polyco matrix green fingerless',
  'quick release hose clamps',
  'Router',
  'scalpel blades',
  'sds max chisel',
  'sharps bin',
  'Shovel',
  'stanley tape',
  'swiss riffler file',
  'Tap',
  'tapping compound',
  'Taps',
  'toggle clamps',
  'wire brush hand',
  '1 inch socket sets',
  '110v die grinder',
  '3m mask',
  'aaa batterys',
  'allen socket set',
  'Ansell TouchNTuff 92-500',
  'axe',
  'bsf taps and dies for sale',
  'bubblewrap',
  'carabiner',
  'ceramic grinding wheels',
  'Ejendals Tegera 983',
  'electric water displacement spray',
  'faithful waterproofs',
  'garden tools',
  'giok gloves',
  'Grinder',
  'hozelock',
  'internal external caliper',
  'iscar parting inserts',
  'junior hacksaw blade',
  'kennedy af spanner set',
  'knurling tools',
  'kobe sander',
  'magnetic drill bit holder',
  'mig welding nozzle',
  'mitutoyo bore gauge',
  'norton cutting disc',
  'Pillar drill',
  'post rammer',
  'spades',
  'speedglas 9100x lens',
  'spring ball plunger',
  'traffic cone',
  'tube cutter',
  'welding blanket',
  'yellow floor paint concrete',
  '12mm end mills',
  '3m filter',
  '55mm spanner',
  '9123 Tegera',
  'adjustable pipe grips',
  'ansell 37-900',
  'Bench grinder',
  'bolle anti fog safety glasses',
  'bt40',
  'Centre punch',
  'drills sharpener',
  'drum tap',
  'end milling cutter',
  'face grooving tools turning',
  'flap discs',
  'hand shovel',
  'impact driver bit set',
  'lifting eyebolt',
  'makita reciprocating saw blades',
  'model engineering tools for sale',
  'murex welding nozzles',
  'pencils',
  'plunger',
  'Racking',
  'ring spanner set',
  'safety helmet protection',
  'shackle',
  'short spanners',
  'sockets set',
  'spill granules',
  'tape measure 10m',
  'tegera 320',
  'threaded black plastic ball knob',
  'tool roll',
  'Trolley jack',
  'workshop trolleys',
  '3m speedglas 9100',
  '8mm spanner',
  'ansell 23-700',
  'barrow',
  'Bolts',
  'bore micrometer',
  'bubble wrap roll',
  'compression springs',
  'dcf899p2',
  'diamond files for carbide',
  'die stock',
  'evolution 355mm',
  'Fluke',
  'Hammers',
  'hi vis goretex coverall',
  'hook on grease nipple',
  'ibc',
  'kennedy socket extension bar 1 2',
  'Kennedy20',
  'loctite 222',
  'long series drills',
  'm4 machine tap',
  'magnifier',
  'mandrel',
  'oil filter removal tool',
  'Podger',
  'powered torque wrench',
  'reflective tape',
  'sds drills',
  'secateurs',
  'Shoes',
  'solent cleaning and hygiene',
  'Stanley knife',
  'Tegera 9122',
  'terry tool clips',
  'Thread Gauges',
  'unc 4 40 tap',
  '0 25mm micrometer',
  '115mm cutting disc',
  '6mm slot drill',
  'Ansell TouchNTuff 92-605',
  'bearings pullers',
  'bosch sander sheets',
  'compression tester',
  'copper/rawhide',
  'deb foam hand wash',
  'deburring tools industrial tools',
  'emery cloth sheets',
  'engineers scriber',
  'fused multimeter leads',
  'GL833',
  'gorilla tape',
  'grind stone',
  'jsp hard hat',
  'kennedy mig welders',
  'mapp gas',
  'metric taps and dies for sale',
  'office supplies',
  'performance pro power tools',
  'permanent markers',
  'pipe cutters',
  'polyco polyflex',
  'puma',
  'pump truck',
  'rachet',
  'ratchet handle',
  'replacement hammer shafts',
  'senator tool boxes',
  'silicon carbide grit',
  'soft face hammer',
  'stationary',
  'tegera 206',
  'trefolex',
  'workbenches',
  'yankee spiral ratchet screwdriver',
  '1 drive impact sockets',
  '10mm nut spinner',
  '22mm spanner',
  '30 mm box spanner',
  '41mm spanner',
  '50mm spanner',
  'air line fittings',
  'air riveter',
  'Ansell TouchNTuff 93-250',
  'Bandsaw',
  'bolle safety spectacle',
  'Burr',
  'centre finder tool',
  'coolant hose fittings',
  'creeper',
  'drill chuck guards',
  'ejendals 139',
  'flexello pressed steel castors',
  'go system gas blow torch',
  'heat resistant paint',
  'heavy duty pry bar chisel and point',
  'inch drive socket set',
  'ipa',
  'kennedy stellite drills',
  'kennedy tool box lock',
  'kennedy vice jaws',
  'magnetic screwdriver bits',
  'makita die grinders',
  'micrometer setting rods',
  'milling cutter',
  'Moore',
  'parweld',
  'pipe grips',
  'platform ladder',
  'Polyco Finite P Indigo AF Nitrile Disposable Gloves MFNP100',
  'ridgid tools for sale',
  'safety harness',
  'screwdriver bit',
  'signage',
  'skytec aria gloves size 10/xl',
  'taper gauge',
  'timberland',
  'Tool case',
  'wedge',
  'Work boots',
  '0 25 micrometer',
  '1/4 drive flexible extension',
  '11 16 deep socket',
  '3 flute carbide drill',
  '32mm spanner',
  '4mm allen key',
  'absorbent pads',
  'af ratchet spanners',
  'artist brush',
  'bacho adjustable',
  'backing pad',
  'black nitrile gloves',
  'blower',
  'brake hose clamp tool',
  'euro air fittings',
  'extractor socket',
  'eye protection',
  'grease gun air',
  'Hacksaw',
  'heavy duty chrome leather welders apron',
  'hose clamp',
  'internal dial caliper gauges',
  'loppers',
  'magnifying loupe',
  'msa safety helmets',
  'perfo panel',
  'plug',
  'pneumatic fittings kits',
  'polyco reflex 861',
  'red oxide',
  'ReturnToWorkBarriers',
  'Safety glasses',
  'saffire 3 welding nozzles',
  'scissor jack',
  'sherwood drill and tap set',
  'Spanners',
  'stanley tape measure',
  'straight grinder',
  'swiss and burr deburring tool blades',
  't25 torx bit',
  'Tegera 9128',
  'terminal screwdriver',
  'threaded rivet nut tool',
  'tig torch consumables',
  'welding aprons',
  '02-100',
  '2mm router cutter',
  '3/8 socket rachet',
  '5 16 unf thread',
  'air ratchet',
  'Ansell TouchNTuff 92-670',
  'bit holder',
  'Cement mixer',
  'chemical resistant gloves en 374',
  'deep throat clamps',
  'defibrillator',
  'Dickies',
  'Ejendals Tegera 843',
  'Ejendals Tegera 9100',
  'f clamp',
  'floodsax',
  'impact wrench dewalt',
  'keyless chuck',
  'leather thickness gauge',
  'louvre storage pannel bins',
  'm10 nut',
  'magnetic stand',
  'mastic gun',
  'matrix f',
  'parweld tig torch',
  'Polyco Polysol',
  'post hole diggers',
  'quick clamps',
  'Rake',
  'ratchet set',
  'retractable barrier',
  'roller cab',
  'router table',
  'SAFETY SHOES',
  'scissor lift',
  'silicon grease',
  'Sockets',
  'spiral bands',
  'spring pin',
  'sun cream',
  'teroson',
  'threadlock loctite 222 50ml',
  'tile cutter',
  'trenching shovels',
  'Uvex safety boots',
  'vde screwdriver set',
  'Wire brush',
  'woodruff',
  'Work trousers',
  'QFT6004496V',
  'QFT6004497W',
  'QFT6004498X',
  'QFT6004499Y',
  'QFT6004500A',
  'QFT6004501B',
  'QFT6004502C',
  'QFT6004504E',
  'QFT6004506G',
  'QFT6004521B',
  'QFT6004523D',
  'QFT6004524E',
  'QFT6004540A',
  'QFT6004541B',
  'QFT6004542C',
  'QFT6004544E',
  'QFT6004561B',
  'QFT6004562C',
  'QFT6004563D',
  'QFT6004564E',
  'QFT6004580A',
  'QFT6004582C',
  'QFT6008048Y',
  'QFT6008049Z',
  'QFT6008050A',
  'QFT6008052C',
  'QFT6008054E',
  'QFT6008056G',
  'QFT6008058J',
  'QFT6008059K',
  'QFT6008061R',
  'QFT6008064G',
  'QFT6008068M',
  'QFT6008119H',
  'QFT6008119K',
  'QFT6008120A',
  'QFT6008121B',
  'QFT6008121C',
  'QFT6008122C',
  'QFT6008123D',
  'QFT6008124E',
  'QFT6008125A',
  'QFT6008125F',
  'QFT6008126G',
  'QFT6008127H',
  'QFT6008127J',
  'QFT6008127K',
  'QFT6008127L',
  'QFT6008127M',
  'QFT6008127N',
  'QFT6008127P',
  'QFT6008127R',
  'QFT6008127T',
  'QFT6008127V',
  'QFT6008128J',
  'QFT6008128K',
  'QFT6008129R',
  'QFT6008130A',
  'QFT6008131B',
  'QFT6008132C',
  'QFT6008132R',
  'QFT6008133D',
  'QFT6008134E',
  'QFT6008135F',
  'QFT6008136G',
  'QFT6008136T',
  'QFT6008137R',
  'QFT6008138F',
  'QFT6008138G',
  'QFT6008138J',
  'QFT6008138L',
  'QFT6008138N',
  'QFT6008139B',
  'QFT6008139G',
  'QFT6008139T',
  'QFT6008140A',
  'QFT6008140C',
  'QFT6008140G',
  'QFT6008140J',
  'QFT6008141A',
  'QFT6008141B',
  'QFT6008141C',
  'QFT6008142C',
  'QFT6008142R',
  'QFT6008142T',
  'QFT6008142U',
  'QFT6008142V',
  'QFT6008142W',
  'QFT6008143A',
  'QFT6008142X',
  'QFT6008143E',
  'QFT6008142P',
  'QFT6008142Q',
  'QFT6008142Y',
  'QFT6008143B',
  'QFT6008143C',
  'QFT6008144A',
  'QFT6008144D',
  'QFT6008144E',
  'QFT6008145F',
  'QFT6008145T',
  'QFT6008146H',
  'QFT6008146J',
  'QFT6008148R',
  'QFT6008149A',
  'QFT6008150G',
  'QFT6008152L',
  'QFT6008165K',
  'QFT6008170J',
  'QFT6008171K',
  'QFT6008172L',
  'QFT6008173M',
  'QFT6008174N',
  'QFT6008176Q',
  'QFT6008177R',
  'QFT6008178S',
  'QFT6008182F',
  'QFT6008182T',
  'QFT6008194T',
  'QFT6009000A',
  'QFT6009001B',
  'QFT6009002C',
  'QFT6009004E',
  'QFT6009005F',
  'QFT6009006G',
  'QFT6009020A',
  'QFT6009021B',
  'QFT6009022C',
  'QFT6009025F',
  'QFT6009026G',
  'QFT6009027H',
  'QFT6009028J',
  'QFT6009040A',
  'QFT6009041B',
  'QFT6009042C',
  'QFT6009045F',
  'QFT6009046G',
  'QFT6009047H',
  'QFT6009048J',
  'QFT6009049K',
  'QFT6009050L',
  'QFT6009052N',
  'QFT6009070A',
  'QFT6009073D',
  'QFT6009074E',
  'QFT6009075F',
  'QFT6009076G',
  'QFT6009077H',
  'QFT6009078J',
  'QFT6009079K',
  'QFT6009081M',
  'QFT6009091B',
  'QFT6009092C',
  'QFT6009093D',
  'QFT6009094E',
  'QFT6009095F',
  'QFT6009097H',
  'QFT6009098J',
  'QFT6009099N',
  'QFT6009100T',
  'QFT6009110A',
  'QFT6009111B',
  'QFT6009112C',
  'QFT6009113D',
  'QFT6009115E',
  'QFT6009116G',
  'QFT6009117H',
  'QFT6009118J',
  'QFT6009119K',
  'QFT6009130A',
  'QFT6009131B',
  'QFT6009132C',
  'QFT6009134E',
  'QFT6001440E',
  'QFT6001440G',
  'QFT6001440J',
  'QFT6001440L',
  'QFT6001440N',
  'QFT6001440S',
  'QFT6001442E',
  'QFT6001442G',
  'QFT6001442J',
  'QFT6001442L',
  'QFT6001442N',
  'QFT6001442S',
  'QFT6001442X',
  'QFT6001445C',
  'QFT6001445E',
  'QFT6001445G',
  'QFT6001445J',
  'QFT6001445L',
  'QFT6001445N',
  'QFT6001445Q',
  'QFT6001445S',
  'QFT6001445V',
  'QFT6001445X',
  'QFT6001446B',
  'QFT6001446D',
  'QFT6001446F',
  'QFT6001446H',
  'QFT6001446K',
  'QFT6001446R',
  'QFT6001448C',
  'QFT6001448E',
  'QFT6001448G',
  'QFT6001448J',
  'QFT6001448L',
  'QFT6001448N',
  'QFT6001448Q',
  'QFT6001448S',
  'QFT6001448V',
  'QFT6001448Z',
  'QFT6001449B',
  'QFT6001449D',
  'QFT6001449F',
  'QFT6001449H',
  'QFT6001449K',
  'QFT6001449R',
  'QFT6001449T',
  'QFT6001449W',
  'QFT6001459C',
  'QFT6001459E',
  'QFT6001459G',
  'QFT6001459J',
  'QFT6001459N',
  'QFT6001459S',
  'QFT6001459V',
  'QFT6001459X',
  'QFT6001459Z',
  'QFT6001460B',
  'QFT6001460D',
  'QFT6001460F',
  'QFT6001460H',
  'QFT6001460K',
  'QFT6001460M',
  'QFT6001460P',
  'QFT6001460R',
  'QFT6001460W',
  'QFT6001461A',
  'QFT6001461C',
  'QFT6001461E',
  'QFT6001461J',
  'QFT6001462V',
  'QFT6001462Z',
  'QFT6001463D',
  'QFT6001463H',
  'QFT6001463K',
  'QFT6001463M',
  'QFT6001463P',
  'QFT6001463R',
  'QFT6001463T',
  'QFT6001463W',
  'QFT6001463Y',
  'QFT6001464A',
  'QFT6001464C',
  'QFT6001464E',
  'QFT6001464G',
  'QFT6001464L',
  'QFT6001464Q',
  'QFT6001464S',
  'QFT6001464V',
  'QFT6001464X',
  'QFT6001465A',
  'QFT6001465C',
  'QFT6001467C',
  'QFT6001467G',
  'QFT6001467J',
  'QFT6001467L',
  'QFT6001467N',
  'QFT6001467Q',
  'QFT6001467S',
  'QFT6001467V',
  'QFT6001467X',
  'QFT6001467Z',
  'QFT6001468B',
  'QFT6001468D',
  'QFT6001468F',
  'QFT6001468K',
  'QFT6001468P',
  'QFT6001468R',
  'QFT6001468T',
  'QFT6001468W',
  'QFT6001469A',
  'QFT6001471C',
  'QFT6001471E',
  'QFT6001473G',
  'QFT6001473J',
  'QFT6001473L',
  'QFT6001473N',
  'QFT6001473S',
  'QFT6001473X',
  'QFT6001473Z',
  'QFT6001474B',
  'QFT6001474D',
  'QFT6001474P',
  'QFT6001474W',
  'QFT6001474Y',
  'QFT6001480A',
  'QFT6001480E',
  'QFT6001480J',
  'QFT6001480S',
  'QFT6001481B',
  'QFT6001485Q',
  'QFT6000905F',
  'QFT6000906G',
  'QFT6000912N',
  'QFT6000913P',
  'QFT6000914Q',
  'QFT6000915R',
  'QFT6000916S',
  'QFT6000917T',
  'QFT6000918V',
  'QFT6000918Y',
  'QFT6000919X',
  'QFT6000920T',
  'QFT6000920X',
  'QFT6000921Y',
  'QFT6000922Z',
  'QFT6000924A',
  'QFT6000925B',
  'QFT6000925R',
  'QFT6000926F',
  'QFT6000927C',
  'QFT6000927D',
  'QFT6000928E',
  'QFT6000929F',
  'QFT6000930G',
  'QFT6000931H',
  'QFT6000932J',
  'QFT6000934L',
  'QFT6000934M',
  'QFT6000935M',
  'QFT6000935Z',
  'QFT6000936N',
  'QFT6000937P',
  'QFT6000938Q',
  'QFT6000939C',
  'QFT6000939E',
  'QFT6000939F',
  'QFT6000939H',
  'QFT6000976F',
  'QFT6000976E',
  'QFT6000977F',
  'QFT6000978G',
  'QFT6000979H',
  'QFT6000981K',
  'QFT6000982L',
  'QFT6000983M',
  'QFT6000984N',
  'QFT6000985P',
  'QFT6000986Q',
  'QFT6000987R',
  'QFT6000988S',
  'QFT6000989T',
  'QFT6000990V',
  'QFT6000991W',
  'QFT6000992X',
  'QFT6000993Y',
  'QFT6000994Z',
  'QFT6000996A',
  'QFT6000997B',
  'QFT6000997C',
  'QFT6000998C',
  'QFT6000999D',
  'QFT6001000E',
  'QFT6001001F',
  'QFT6001001H',
  'QFT6001001K',
  'QFT6001001P',
  'QFT6001001T',
  'QFT6001001V',
  'QFT6001001W',
  'QFT6000939R',
  'QFT6000940S',
  'QFT6000941T',
  'QFT6000942V',
  'QFT6000943W',
  'QFT6000944X',
  'QFT6000946Z',
  'QFT6000947F',
  'QFT6000948A',
  'QFT6000948G',
  'QFT6000949B',
  'QFT6000950C',
  'QFT6000951D',
  'QFT6000952E',
  'QFT6000953F',
  'QFT6000954G',
  'QFT6000954W',
  'QFT6000954Z',
  'QFT6000955A',
  'QFT6000955B',
  'QFT6000955C',
  'QFT6000955D',
  'QFT6000955G',
  'QFT6000955E',
  'QFT6000955H',
  'QFT6000956J',
  'QFT6000957K',
  'QFT6000958L',
  'QFT6000959M',
  'QFT6000961P',
  'QFT6000962Q',
  'QFT6000963R',
  'QFT6000964S',
  'QFT6000965T',
  'QFT6000966V',
  'QFT6000967W',
  'QFT6000968X',
  'QFT6000969Y',
  'QFT6000970Z',
  'QFT6000972A',
  'QFT6000973B',
  'QFT6000974C',
  'QFT6000975D',
  'QFT6000975K',
  'QFT6000975R',
  'QFT6000975S',
  'QFT6000975T',
  'QFT6000975X',
  'QFT6000975Z',
  'QFT6000976A',
  'QFT6000976B',
  'QFT6000976C',
  'QFT6000976D',
  'QFT6001002G',
  'QFT6001003H',
  'QFT6001006L',
  'QFT6001007M',
  'QFT6001008N',
  'QFT6001009P',
  'QFT6001010Q',
  'QFT6001011R',
  'QFT6001012S',
  'QFT6001013T',
  'QFT6001014V',
  'QFT6001015W',
  'QFT6001016X',
  'QFT6001017Y',
  'QFT6001018Z',
  'QFT6001020A',
  'QFT6001021B',
  'QFT6001022C',
  'QFT6001023A',
  'QFT6001023D',
  'QFT6001024E',
  'QFT6001025F',
  'QFT6001026G',
  'QFT6001027H',
  'QFT6001028J',
  'QFT6001029K',
  'QFT6001030L',
  'QFT6001031M',
  'QFT6001032N',
  'QFT6001033P',
  'QFT6001034Q',
  'QFT6001037T',
  'QFT6001038V',
  'QFT6001039W',
  'QFT6001041Y',
  'QFT6001042Z',
  'QFT6001044A',
  'QFT6001045B',
  'QFT6001046C',
  'QFT6001047D',
  'QFT6001048E',
  'QFT6001049F',
  'QFT6001050G',
  'QFT6001051H',
  'QFT6001052J',
  'QFT6001053K',
  'QFT6001054L',
  'QFT6001055M',
  'QFT6001056N',
  'QFT6001057P',
  'QFT6001058Q',
  'QFT6001059R',
  'QFT6001060S',
  'QFT6001061T',
  'QFT6001062V',
  'QFT6001063W',
  'QFT6001063Y',
  'QFT6001064A',
  'QFT6001064B',
  'QFT6001064L',
  'QFT6001064X',
  'QFT6001068A',
  'QFT6001070C',
  'QFT6001072E',
  'QFT6001073F',
  'QFT6001074G',
  'QFT6001075H',
  'QFT6001076J',
  'QFT6001077K',
  'QFT6001078L',
  'QFT6001079M',
  'QFT6001080N',
  'QFT6001081P',
  'QFT6001082Q',
  'QFT6001083R',
  'QFT6001083S',
  'QFT6001084S',
  'QFT6001085T',
  'QFT6001086V',
  'QFT6001087W',
  'QFT6001088X',
  'QFT6001089Y',
  'QFT6001090Z',
  'QFT6001092A',
  'QFT6001093B',
  'QFT6001094C',
  'QFT6001094E',
  'QFT6001094G',
  'QFT6001094J',
  'QFT6001094Q',
  'QFT6001094S',
  'QFT6001095D',
  'QFT6001096E',
  'QFT6001097F',
  'QFT6001098G',
  'QFT6001099H',
  'QFT6001100J',
  'QFT6001101K',
  'QFT6001102L',
  'QFT6001103M',
  'QFT6001104N',
  'QFT6001105P',
  'QFT6001106Q',
  'QFT6001107R',
  'QFT6001109T',
  'QFT6001110F',
  'QFT6001110V',
  'QFT6001110Z',
  'QFT6001111E',
  'QFT6001112X',
  'QFT6001113Y',
  'QFT6001114Z',
  'QFT6001116A',
  'QFT6001117B',
  'QFT6001118C',
  'QFT6001119D',
  'QFT6001120E',
  'QFT6001121F',
  'QFT6001122G',
  'QFT6001123H',
  'QFT6001124J',
  'QFT6001125A',
  'QFT6001125K',
  'QFT6001126L',
  'QFT6001127M',
  'QFT6001128N',
  'QFT6001129P',
  'QFT6001130Q',
  'QFT6001131R',
  'QFT6001132S',
  'QFT6001133T',
  'QFT6001134V',
  'QFT6001134X',
  'QFT6001134Y',
  'QFT6001136D',
  'QFT6001136H',
  'QFT6001134Z',
  'QFT6001135W',
  'QFT6001140A',
  'QFT6001142C',
  'QFT6001144E',
  'QFT6001146G',
  'QFT6001147H',
  'QFT6001148J',
  'QFT6001151M',
  'QFT6001152N',
  'QFT6001153P',
  'QFT6001154Q',
  'QFT6001155R',
  'QFT6001156S',
  'QFT6001157T',
  'QFT6001158V',
  'QFT6001159W',
  'QFT6001160X',
  'QFT6001161Y',
  'QFT6001162Z',
  'QFT6001164A',
  'QFT6001165B',
  'QFT6001166C',
  'QFT6001167D',
  'QFT6001168E',
  'QFT6001169F',
  'QFT6001170G',
  'QFT6001171H',
  'QFT6001172J',
  'QFT6001173K',
  'QFT6001174L',
  'QFT6001175M',
  'QFT6001176N',
  'QFT6001177P',
  'QFT6001180S',
  'QFT6001181T',
  'QFT6001182V',
  'QFT6001183W',
  'QFT6001184X',
  'QFT6001184Y',
  'QFT6001186Z',
  'QFT6001188A',
  'QFT6001189B',
  'QFT6001190C',
  'QFT6001191D',
  'QFT6001192E',
  'QFT6001193F',
  'QFT6001194G',
  'QFT6001195H',
  'QFT6001196J',
  'QFT6001197K',
  'QFT6001198L',
  'QFT6001199M',
  'QFT6001200N',
  'QFT6001201P',
  'QFT6001202Q',
  'QFT6001204S',
  'QFT6001207W',
  'QFT6001208X',
  'QFT6001209Y',
  'QFT6001212A',
  'QFT6001215D',
  'QFT6001218G',
  'QFT6001220J',
  'QFT6001222L',
  'QFT6008101Q',
  'QFT6008102R',
  'QFT6008103F',
  'QFT6008104A',
  'QFT6008105B',
  'QFT6008105T',
  'QFT6008106C',
  'QFT6008106D',
  'QFT6008106F',
  'QFT6008107A',
  'QFT6008107J',
  'QFT6008107L',
  'QFT6008107M',
  'QFT6008108R',
  'QFT6008109J',
  'QFT6008110A',
  'QFT6008111B',
  'QFT6008111D',
  'QFT6008112C',
  'QFT6008113D',
  'QFT6008114E',
  'QFT6008115F',
  'QFT6008115G',
  'QFT6008116G',
  'QFT6008117A',
  'QFT6008117J',
  'QFT6008118J',
  'QFT6001455A',
  'QFT6001455C',
  'QFT6001455E',
  'QFT6001455G',
  'QFT6001455J',
  'QFT6001455L',
  'QFT6001455N',
  'QFT6001455Q',
  'QFT6001455S',
  'QFT6001455V',
  'QFT6001455X',
  'QFT6001455Z',
  'QFT6001456B',
  'QFT6001456D',
  'QFT6001456F',
  'QFT6001456H',
  'QFT6001456K',
  'QFT6001456M',
  'QFT6001456P',
  'QFT6001456R',
  'QFT6001456T',
  'QFT6001456Y',
  'QFT6001457C',
  'QFT6001451C',
  'QFT6001451E',
  'QFT6001451G',
  'QFT6001451J',
  'QFT6001451L',
  'QFT6001451N',
  'QFT6001451Q',
  'QFT6001451S',
  'QFT6001451X',
  'QFT6001451Z',
  'QFT6001452B',
  'QFT6001452D',
  'QFT6001452F',
  'QFT6001452H',
  'QFT6001452K',
  'QFT6001452M',
  'QFT6001452R',
  'QFT6001452W',
  'QFT6001453E',
  'kennedy tools',
  'Kennedy Tools',
  'Kennedy tools',
  'kennedy Tools',
  'KENNEDY TOOLS',
  'Kennedy Professional',
  'kennedy professional',
  'Kennedy Professional Tools',
  'kennedy professional tools',
  'kennedy professional hand tools',
  'Kennedy Professional Hand Tools',
  'Bosch DIY',
  'bosch diy',
  'bosch professional',
  'Bosch Professional',
  'bosch professional tools',
  'Bosch Professional Tools',
  'bosch pro deals',
  'Bosch Pro Deals',
  'Bosch PRO Deals',
  'Bosch Green',
  'bosch green',
  'bosch green tools',
  'Bosch Green Tools',
  'bosch blue',
  'Bosch Blue',
  'bosch blue tools',
  'Bosch Blue Tools',
  'molykote grease',
  '3m fast cut compound',
  'makita grinder',
  'fragile tape',
  '1/8 bsp tap',
  'worklight',
  'anvil',
  '13mm combination spanner',
  'Superclamp',
  '16mm spigot',
  'PLY9610122D',
  'hex bit socket set',
  'polyester strapping',
  'transfer pump',
  'thread mill',
  'letter stamp set',
  'gas shrink gun',
  'dewalt angle grinder',
  'soluble oil',
  'adjustable reamer',
  'bell',
  'alan key',
  'gt85',
  'corner radius end mill',
  'putty knife',
  'personal care kit',
  'hop up',
  'swiss and burr deburring tool blades',
  'safety barrier system',
  'vise',
  'biscuits',
  'sink',
  'hex nuts',
  'womens puma safety shoes',
  'roloc holder',
  'space heater',
  'drill insert',
  'water hose reel',
  'tipping skip',
  'a4 packing envelopes',
  'hammer wedge',
  'fire extinguisher stand',
  'cat',
  '150mm backing pad 5 16',
  '1/4 torque wrench',
  't handle',
  'R8',
  'blue',
  'paper thickness micrometer gauge',
  'picks',
  'bulldog garden rakes',
  'safety barrier chain',
  'marking gauge',
  'clamp screw',
  'milwaukee grinder',
  'strapping tool',
  'thermal vest',
  'flame retardant jacket',
  'gaffa tape',
  'Osaki',
  'qmax',
  'open ended spanner set',
  'maglite torch',
  'anti rust paper',
  'quick release collet',
  'chamfer',
  'hats',
  'traffic cones',
  'sweeper',
  'motor',
  '14mm socket',
  'black paint',
  'transmission jack',
  'electric drill',
  'threaded insert',
  'bullfinch',
  '2-piece rainsuit',
  'self grip pliers',
  'coshh cupboard',
  'polishing bar',
  'marking tape',
  'locking clamp',
  'jeyes',
  'work mat',
  'clearance',
  'marigold gloves',
  'mixing paddle',
  'loupe',
  'hydraulic ram',
  'adhesive remover',
  'draws',
  'lock out tag out',
  'power drill',
  'air hose fittings',
  'o clip',
  'thickness gauge',
  'torx key set',
  '10mm combination spanner',
  'post box',
  'gvs',
  'magnetic bit holder',
  '15mm hole punch',
  'metal files',
  'kengrip socket',
  'brazing torch',
  'welding magnets',
  'drill blanks',
  'keys',
  '7mm spanner',
  'banding tool',
  'Jacobs',
  'cnc tool trolley',
  'burn first aid kit',
  'milwaukee battery',
  'allen key sockets',
  '15mm spanner',
  'digital angle finder',
  'high vis vest',
  'safety boots size 9',
  'diamond file set',
  'primer paint',
  'aluminium bar',
  'nail puller',
  '3m bristle brush',
  'sand bag',
  'toolkit',
  'gasket paper',
  'pedestal fan',
  'pozi screwdriver',
  'plane',
  'safety locking wire',
  'plastic bins',
  'welding electrodes',
  'oil filled radiator',
  'tables',
  'laptop riser',
  'extractor tool',
  'c batteries',
  'bib',
  'granules',
  'm4 tap set',
  'grip tape',
  'wypall cleaning wipes',
  'dovetail cutter',
  '5c collet',
  'hydraulic pump',
  'gauges',
  'step block',
  '36mm impact socket',
  'osaki power tools',
  'puma safety boots',
  'skates',
  'sledgehammer',
  'permabond',
  'polythene bags',
  'ball joint',
  'kennedy crimping tool',
  'ct1',
  'HellermannTyton',
  'linbin',
  'tap and drill set',
  '3/8 torque wrench',
  'air rivet gun',
  'heat resistant gauntlet',
  'clear bags',
  'asbestos',
  'fairy liquid',
  'fluke multimeter',
  'tubs',
  'avon',
  'm10 bolt',
  'recycling bins',
  'tapping fluid',
  'welding pliers',
  'stanley level',
  'nylon',
  'grooving insert',
  'metric lathe thread cutting tool',
  'cardboard box',
  'ITL Insulated Tools Ltd',
  'Mitsubishi',
  'fall arrest',
  'heli coil',
  'crawler board',
  'lifting magnet',
  'unc tap',
  'notebook',
  'extraction',
  'action can',
  'face sheild',
  'engineers file set',
  'indexa seiki',
  '1/4 extension',
  'tool tray',
  'counterbore tool',
  'impact drill',
  'bosch cordless drill',
  'little giant',
  'hose fitting',
  'knurl',
  'bulldog garden tools',
  'parts cleaner',
  'parting',
  'crows feet',
  'dewalt tstak box',
  'wire cup brush',
  't-shirt',
  'vibration gloves',
  'paint sprayer',
  'spiraband',
  'lifting slings',
  'drum porter',
  '38mm socket',
  '14mm hex key',
  'kennedy punch set',
  'yellow spray paint',
  'granite',
  'kennedy hole saw',
  '3/4 ratchet',
  'rawl plugs',
  'car battery charger',
  'bsp tap set',
  'oil pads',
  'tfr',
  'cutting disks',
  'mugs',
  'steel clear lacquer',
  'welding clamp',
  'handwash',
  'locline',
  'thread pitch gauge',
  'kennedy pro',
  'sika',
  'pass through socket',
  'high lift truck=pallet',
  'flooring',
  'driver',
  'coupler',
  'gripseal bags',
  'ear protection sign',
  'oil free air compressor',
  'petroleum jelly',
  'shoe laces',
  'pat tester',
  'multi-purpose cleaner',
  'hardness tester',
  'power file',
  'adjustable square',
  'molykote 1000',
  'metal cleaner',
  'notepads',
  'cigarette',
  'm6 bolt',
  '12mm allen key',
  'computer',
  'lighter',
  'kobe drill spares',
  'Simoniz',
  'swivel handle',
  'sander backing pad',
  'himalayan safety boots',
  'Norton st gobain',
  'Norton st-gobain',
  'Norton',
  'Norton Saint-Gobain',
  'Norton Saint Gobain',
  'Saint-gobain',
  'Saint Gobain',
  'Norton Abrasives',
  'Saint-Gobain Abrasives',
  'KNIPEX',
  'Knipex',
  'knipex',
  'knipex cutters',
  'Kimberly Clark',
  'Kimberly Clark Professional',
  'Kimberly-Clark',
  'Kimberly-Clark Professional',
  'Kimberly Clarke',
  'Kimberley Clark',
  'Kimberley Clark Professional',
  'Kimberly Clarke Professional',
  'Scott Hygiene',
  'Kleenguard',
  'Kleenex',
  'RightCycle',
  'Rightcycle',
  'rightcycle',
  'new product',
  'New Product',
  'new products',
  'New Products',
  'newproduct',
  'newproducts'
];
