exports.synonyms = ['allen,hex,alan,allen,alen',
'anti bacterial,anti bac,antibac,antibacterial',
'anti freeze,antifreeze',
'axe,hatchet',
'bandsaw,band saw',
'bar,rod',
'bassine broom,broom head',
'battery tools,cordless power tool',
'bench drilling,pillar drill,drill press',
'bench sander,bench grinder',
'bench saw,table saw',
'binder clips,filing clips',
'biro,ballpoint',
'bolt cropper,bolt cutter',
'bookcase,book case',
'breaker bar head,swivel handle',
'brush,brushware,broom,sweeper',
'burette,needle files',
'caliper,calliper,vernier',
'cam shaft,camshaft',
'cap head,socket cap',
'cap screws,socket caps',
'car,vehicle,automotive',
'caster,castor',
'caulking gun,sealant gun,mastic gun',
'chain saw,chainsaw',
'chop saws,cut-off saw',
'chucks,drill chuck',
'cockpit shine,dashboard',
'collet holders,collet chuck',
'compound mitre saw,mitre saws ',
'computer,pc',
'cone cutter,hss step drill',
'copper slip,anti seize compound',
'counter clicker,tally counters',
'countersinks aircraft,countersink',
'de walt,dewalt',
'desk,workstation',
'detergent,dishwash,laundry',
'dial test indicator,dti',
'diamond coated,diamond',
'dieheads,die heads',
'disc,disk',
'distilled,deionised',
'doc marten,drmarten,dr marten',
'document stamp,date stamp,text stamp',
'draughtsman,draftsman',
'drill batteries,power tool batteries',
'drill guard,chuck guard',
'drill screwdriver,cordless screwdriver',
'drill sds,sds-style bits',
'dust collection,extraction,dust extractor',
'dust pan,dustpan',
'engraving,stenciling',
'extending,extendable',
'extractor,remover',
'fabric markers,laundry markers',
'fibreglass,fibre glass',
'fire,flame',
'fire retardant overalls,coverall fr',
'floor mat,chair mat',
'food grade,food safe',
'footrest,foot rest',
'gasket hole punches,hollow punch',
'gear puller,mechanical puller',
'glue,sticker,adhesive',
'goose neck,offset',
'goretex,gore-tex',
'ground flat bar,ground flat stock',
'grub screw,set screws',
'grub screws,set screws',
'hat stands,coat stands',
'heli coil,helicoil,thread insert',
'hole deburring,deburring tools,carbide burrs',
'hole saw,holesaw,holesaw,hole saw replacement drill,holesaw arbor',
'hoover,vaccum,sucker,vacuum cleaner',
'hose pipe,hosepipe,hose',
'impact drill,percussion drill',
'impact gun,impact wrench',
'impact screwdriver,impact driver',
'jig saw,jigsaw',
'keysafe,key safe',
'l shaped desk,crescent shaped desk,radial shaped desk',
'lamp,light,floodlight,worklight',
'lift trolley,lift table',
'linisher,belt & disc sander',
'locking pliers,grip wrench',
'lorry strap,load strap',
'mag drill,magnetic drill',
'magnifying glass,hand magnifiers',
'masking paper,masking tape',
'men,man,male',
'metal file,engineers file',
'milling,milling machine',
'milling machine vices,machine vices',
'milling vice,machine vices',
'mititoyo,mitutoyo',
'mitre compound saw,electric mitre saw',
'mitre compound saw,mitre saws',
'mole grip,grip wrench',
'mouse,mice',
'nail drill,nailer',
'ni-mh,nimh',
'nicd,nicad,nickel cadmium',
'noise,sound',
'nylon pneumatic pipe,tubing',
'oil stone,oilstone',
'paint container,paint kettle',
'pallet strapping,pallet wrap,stretch wrap',
'pass-thru,go-thru',
'penetrant,penetration',
'plasti-kote,plastikote',
'plumbers wrench,pipe wrench',
'pocket hole,self tappers',
'polishing machine,electric polisher',
'port west,portwest',
'portable transfer,dual transfer',
'posdrive,pz',
'power craft tools,engraving',
'power drill,electric drill',
'powertools,power tools',
'prybar,pry bar',
'reciprocating saw blade,sabre',
'recyclingbin,recycling bin',
'reisser,wood screws',
'rotabroach bit,milling cutters',
'rotary ball files,rotary burrs',
'router bit,router cutter',
'router plane,rebate plane',
'rule,ruler',
'sandpaper,sand paper',
'scnoor washers,safety washers',
'screenwash,screen wash ',
'sealskin,sealskinz',
'set,kit',
'signage,sign,notice',
'sledgehammer,sledge hammer',
'spanner,wrench',
'splitter,separator,breaker',
'straight grinders,die grinder',
'straightedge,straight edge',
'svjbr1616,sandvik toolholder',
'swivel vice,machine vice',
'tamperproof screws,security screws',
'thread gauges,screw gauges',
'through,thru',
'snip,snipper,tinsnipper,tinsnip,tin snip,tin snipper',
'tippex,correction',
'tool box,toolbox,tool case',
'toolkit,tool kit',
'toolsteel,tool steel',
'trolley wheel,wheels',
'turnbuckle,straining screws',
'unified,unf',
'unistrut,channel nuts',
'united states of america,usa',
'valve remover,valve compressor',
'van vault,van box,truck box',
'vise grip,grip wrench,wisegrip,visegrip',
'washing,cleaning',
'waterproof,water proof',
'waterpump,water pump ',
'welding mask,welding helmet',
'wellingtons,wellies',
'wheel,dolly,dollies',
'wire cutting,diagonal cutting pliers',
'women,woman,female',
'workstation,desk',
'silversteel,silver steel ',
'wheelbarrow,wheel barrow ',
'fire exstinghuster,fire extinguisher',
'air con,air conditioning ',
'oil jug,oil cans',
'suncream,sun cream',
'lapel pin,label pin',
'woodscrews,wood screws ',
'smoking bin,ash bin',
'elastic bands,rubber bands',
'screw eye,eye bolt,eyebolt',
'wiggler,centre finder',
'centre locator,centre finder',
'wobbler,centre finder',
'walkie-talkie,two way radio',
'lifting straps,leg chain sling',
'door wedge,door stop',
'washerhead,washer head',
'white spirit,paint thinner',
'hook & loop,velcro',
'hellermanntyton,hellermann tyton',
'r8 holder,r8 collet holder',
'refuge sacks,refuse sacks,bin bags,refuse bags',
'deb lime,deb handwash',
'suction puller,lever operated vacuums',
'oring,o ring',
'',
'',
'#### products',
'wd40,wd-40',
'MZ90,MZ-90',
'RX90,RX-90',
'ZG90,ZG-90',
'AC90,AC-90',
'AC90,AC-90',
'AS90,AS-90',
'BC90,BC-90',
'BD90,BD-90',
'CD90,CD-90',
'CD90,CD-90',
'CG90,CG-90',
'CS90,CS-90',
'CT90,CT-90',
'FF90,FF-90',
'TF90,TF-90',
'DS90,DS-90',
'DM90,DM-90',
'EC90,EC-90',
'FC90,FC-90',
'LM90,LM-90',
'WG90,WG-90',
'SA90,SA-90',
'SC90,SC-90',
'SP90,SP-90',
'WB90,WB-90',
'SP90,SP-90',
'RP90,RP-90',
'SL90,SL-90',
'PD90,PD-90',
'TW90,TW-90',
'',
'',
'#### misspellings (more than 2 differences only)',
'seacautears,secateurs',
'',
'',
'#### disabled spelling synonyms',
'#kobo,kobe',
'#ming welder,mig welder',
'#hand ingraver,hand engraver',
'#condut cable,conduit cable',
'#coolnt nozzle,coolant nozzle ',
'#deburrer,deburer',
'#kenedy,kennedy',
'#knippex,knipex',
'#ingersoll,ingersol ',
'#panel,panal,pannel',
'#speedglass,speedglas',
'#laquer,lacquer',
'#selant,sealant',
'#pedistal,pedestal',
'#insecsion glass,inspection glass',
'#nitrle,nitrile',
'#separator,seperator',
'#faithfull,faithful',
'#eastwing,estwing',
'',
'',
'',
'#### metalworking synonyms',
'303,Stainless steel',
'304,Stainless steel',
'316,Stainless steel',
'Ali,Aluminium',
'Allen Key,Hex key',
'Alum,Aluminium',
'American Size,Imperial',
'Bottoming Tap,Third tap',
'Bridgeport Tooling,r8 tooling',
'Butt Weld,turning toolholder',
'CBN,Cubic boron nitride',
'CMM,Coordinate measuring machine ',
'CNC,Computerised numerical control ',
'Combi,Combination,Combined',
'Coolant,Cutting oil',
'Corner Rounder,Corner rounding end mill',
'C-Sink,countersink',
'Cut Off Blade,Part off blade',
'Cutter,End mill,Slot mill',
'Cutting Length,Flute length',
'D2,tool steel',
'Deg,Degree',
'Die Nut,hex die,hexagon die',
'Drill Bit,drill',
'Drill Fix,u-drill',
'DTI,Dial test indicator ',
'EN16,Mild steel',
'EN24,Mild steel',
'EN8,Mild steel',
'English Size,metric',
'Emery Cloth,cloth roll',
'FC3 Cutter,Disposable end mills',
'Feather Key,Radius end key steel  ',
'Finishing Cutter,Finishing end mill',
'Flat Ground Stock,Ground flat stock',
'Flatted Shank,Weldon shank',
'Gauge Blocks,Slip gauges',
'Gauge Plate,Ground flat stock',
'Grub Screws,Socket set screws ',
'Helicoil,Thread repair insert',
'Helicoil Tap,Screw thread insert tap',
'HSS,High speed steel',
'HSSCo - 8%,8 % Cobalt',
'HSS-E,Cobalt',
'Huntington Dresser,Grinding wheel dresser',
'Internal Tooholder,Boring bar',
'Jenny Caliper,Odd leg caliper',
'Hermaphrodite Caliper,Odd leg caliper',
'Jerry Can,Petrol can',
'Joey Blocks,Slip gauges',
'Keyseat Cutter,Woodruff cutter',
'Linishing Disc,Fibre disc',
'M2,High speed steel',
'M35,5% cobalt',
'M42,8-11 % cobalt',
'Mag Base,Magnetic base',
'MDT,Multi directional tooling',
'Mic,Micrometer',
'Mole Grips,Locking pliers',
'MT1,Morse taper 1',
'MT2,Morse taper 2',
'MT3,Morse taper 3',
'MT4,Morse taper 4',
'MT5,Morse taper 5',
'Necked,Reduced Shank',
'PCD,Pollycrystalline diamond ',
'Philidas Pins,Socket head shoulder screws  ',
'Pig Sock,Absorbent sock',
'Plug Tap,Bottom tap',
'Rad,Radius',
'Retention Knob,Pull stud',
'Rippers,Roughing end mills',
'Roll Tap,Fluteless Tap,Roll Form Tap',
'Rounded Shank,Parallel shank',
'Router,Single flute end mill',
'Sanding Belt,Linishing belt',
'Sanding Disc,Fibre disc',
'Sanding Pad,Fibre disc',
'SC,Solid carbide',
'Seat,Shim',
'Selloc Pins,Roll pins,Slotted spring pins',
'Shank Mounted Abrasive Wheel,Mounted point',
'Shim In A Can,Shim steel',
'Slitting Disc,Cutting disc',
'Slot Drill,Flute milling cutter',
'Slotted Shank,Weldon shank',
'Soft Pad,Fibre disc',
'Stripper Bolts,Socket head shoulder screws  ',
'Suds,Cutting fluid',
'SW,Spindle wiper',
'Tailstock Centre,Live centre',
'First Tap,Taper tap',
'Throwaway cutters,Disposable end mills',
'Tips,Inserts',
'Toolsteel,Toolbit',
'TPI,Teeth per inch',
'Tundish,Cone funnel',
'Tungsten Carbide,Carbide',
'Twist Drill,Jobber drill',
'U Drill,Indexable drill',
'VDI Tooling,Driven toolholders',
'Vernier,Caliper',
'Weldon,Slotted shank',
'Wiggler,Centre finder',
'Wrench,Spanner'];
